import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Worker Lane 与任务执行","description":"","frontmatter":{},"headers":[],"relativePath":"projects/hermes/kanban/Worker Lane 与任务执行.md","filePath":"projects/hermes/kanban/Worker Lane 与任务执行.md"}');
const _sfc_main = { name: "projects/hermes/kanban/Worker Lane 与任务执行.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="worker-lane-与任务执行" tabindex="-1">Worker Lane 与任务执行 <a class="header-anchor" href="#worker-lane-与任务执行" aria-label="Permalink to &quot;Worker Lane 与任务执行&quot;">​</a></h1><p>这篇笔记整理自 <code>kanban-worker-lanes.md</code>，用于理解 Kanban 任务卡是如何被真正执行的。</p><h2 id="worker-lane-是什么" tabindex="-1">Worker lane 是什么 <a class="header-anchor" href="#worker-lane-是什么" aria-label="Permalink to &quot;Worker lane 是什么&quot;">​</a></h2><p>Worker lane 可以理解为“任务执行通道”。</p><p>一张 Kanban 卡被分配给某个 <code>assignee</code> 后，dispatcher 需要知道：</p><ul><li>这个 <code>assignee</code> 代表谁</li><li>怎么启动它</li><li>它启动后必须如何结束任务</li><li>它失败时系统如何处理</li></ul><p>所以一个 lane 至少包含三件事：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>assignee string  分配标识</span></span>
<span class="line"><span>spawn mechanism  启动方式</span></span>
<span class="line"><span>lifecycle contract  生命周期契约</span></span></code></pre></div><h2 id="层级关系" tabindex="-1">层级关系 <a class="header-anchor" href="#层级关系" aria-label="Permalink to &quot;层级关系&quot;">​</a></h2><p>原文给出的层级可以这样理解：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Hermes Kanban  =  任务生命周期与审计真相</span></span>
<span class="line"><span>Worker lane    =  某张任务卡的执行者</span></span>
<span class="line"><span>Reviewer       =  审查并决定是否真的完成的人或代理</span></span>
<span class="line"><span>GitHub PR      =  可选的代码交付物</span></span></code></pre></div><p>关键点是：</p><blockquote><p>Kanban 拥有任务生命周期的真相，worker lane 只是执行任务，不能自己绕过 Kanban 改写状态。</p></blockquote><p>worker 做的任何事，最后都应该通过 <code>kanban_*</code> 工具或 API 回写到 Kanban。</p><h2 id="一个-lane-必须提供什么" tabindex="-1">一个 lane 必须提供什么 <a class="header-anchor" href="#一个-lane-必须提供什么" aria-label="Permalink to &quot;一个 lane 必须提供什么&quot;">​</a></h2><h3 id="_1-assignee-string" tabindex="-1">1. assignee string <a class="header-anchor" href="#_1-assignee-string" aria-label="Permalink to &quot;1. assignee string&quot;">​</a></h3><p><code>task.assignee</code> 是 dispatcher 用来匹配执行者的字段。</p><p>默认情况下，它对应一个 Hermes profile 名称，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>researcher</span></span>
<span class="line"><span>writer</span></span>
<span class="line"><span>reviewer</span></span>
<span class="line"><span>backend-dev</span></span></code></pre></div><p>如果 assignee 找不到，任务不会被随便交给某个 fallback worker，而是留在 <code>ready</code>，并记录类似 <code>skipped_nonspawnable</code> 的事件，方便操作者修复。</p><p>这点很重要：<strong>任务不会因为 assignee 拼错就被错误执行。</strong></p><h3 id="_2-spawn-mechanism" tabindex="-1">2. spawn mechanism <a class="header-anchor" href="#_2-spawn-mechanism" aria-label="Permalink to &quot;2. spawn mechanism&quot;">​</a></h3><p>对默认 Hermes profile lane 来说，dispatcher 会启动类似这样的进程：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>hermes -p &lt;assignee&gt; chat -q &lt;prompt&gt;</span></span></code></pre></div><p>启动时会把任务上下文通过环境变量传进去，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>HERMES_KANBAN_TASK</span></span>
<span class="line"><span>HERMES_KANBAN_DB</span></span>
<span class="line"><span>HERMES_KANBAN_BOARD</span></span>
<span class="line"><span>HERMES_KANBAN_WORKSPACE</span></span>
<span class="line"><span>HERMES_KANBAN_RUN_ID</span></span>
<span class="line"><span>HERMES_KANBAN_CLAIM_LOCK</span></span>
<span class="line"><span>HERMES_PROFILE</span></span>
<span class="line"><span>HERMES_TENANT</span></span></code></pre></div><p>这些变量让 worker 知道：</p><ul><li>当前处理哪张卡</li><li>用哪个 board / DB</li><li>在哪个 workspace 里工作</li><li>当前 run 是哪一次尝试</li><li>自己的 claim lock 是什么</li></ul><h3 id="_3-lifecycle-terminator" tabindex="-1">3. lifecycle terminator <a class="header-anchor" href="#_3-lifecycle-terminator" aria-label="Permalink to &quot;3. lifecycle terminator&quot;">​</a></h3><p>每次 claim 最后必须有一个明确结局：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>kanban_complete(summary=..., metadata=...)</span></span>
<span class="line"><span>kanban_block(reason=...)</span></span>
<span class="line"><span>worker 异常退出 / 超时 / 崩溃</span></span></code></pre></div><p>健康 worker 不应该“写完普通回答就退出”。如果 worker 没有调用 <code>kanban_complete</code> 或 <code>kanban_block</code> 就退出，Kanban 会把它当成协议违规或失败路径。</p><p>这保证了任务状态不会停留在一种模糊状态：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>到底做完了吗？</span></span>
<span class="line"><span>是卡住了吗？</span></span>
<span class="line"><span>还是 worker 死了？</span></span></code></pre></div><h2 id="review-required-约定" tabindex="-1">review-required 约定 <a class="header-anchor" href="#review-required-约定" aria-label="Permalink to &quot;review-required 约定&quot;">​</a></h2><p>对代码修改类任务来说，worker 写完代码不一定代表任务真的完成，因为还需要人类 review。</p><p>这种情况下可以用约定：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>kanban_comment(...)  先写结构化元信息</span></span>
<span class="line"><span>kanban_block(reason=&quot;review-required: ...&quot;)</span></span></code></pre></div><p>这样任务会进入 <code>blocked</code>，表示等待 review。</p><p>Reviewer 可以：</p><ul><li>approve 后 unblock</li><li>comment 要求修改</li><li>让 worker 下一轮读取 comment thread 后继续</li></ul><p>这个设计把“实现完成”和“审查通过”区分开。</p><h2 id="日志和审计" tabindex="-1">日志和审计 <a class="header-anchor" href="#日志和审计" aria-label="Permalink to &quot;日志和审计&quot;">​</a></h2><p>dispatcher 会把每个 worker 的 stdout / stderr 写到任务日志里。</p><p>同时，Kanban 还会记录：</p><ul><li><code>task_runs</code>：每次尝试的 run history，包括 summary、metadata、exit code、log path。</li><li><code>task_events</code>：每次状态变化，例如 claimed、heartbeat、completed、blocked、crashed、timed_out。</li></ul><p>这些信息让 reviewer 或后续 worker 可以不用打开 dashboard，也能通过 <code>kanban_show</code> 看到完整历史。</p><h2 id="现有-lane-类型" tabindex="-1">现有 lane 类型 <a class="header-anchor" href="#现有-lane-类型" aria-label="Permalink to &quot;现有 lane 类型&quot;">​</a></h2><h3 id="hermes-profile-lane" tabindex="-1">Hermes profile lane <a class="header-anchor" href="#hermes-profile-lane" aria-label="Permalink to &quot;Hermes profile lane&quot;">​</a></h3><p>这是默认 lane 类型。</p><p>特点：</p><ul><li>assignee 是 profile 名称</li><li>dispatcher 启动 <code>hermes -p &lt;profile&gt;</code></li><li>worker 加载 <code>kanban-worker</code> skill</li><li>worker 用 <code>kanban_*</code> 工具结束任务</li></ul><p>创建 profile 时，名称最好体现角色，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>researcher</span></span>
<span class="line"><span>writer</span></span>
<span class="line"><span>reviewer</span></span>
<span class="line"><span>backend-dev</span></span>
<span class="line"><span>ops</span></span></code></pre></div><p>这样 orchestrator 才容易把任务路由给合适的 profile。</p><h3 id="orchestrator-profile-lane" tabindex="-1">Orchestrator profile lane <a class="header-anchor" href="#orchestrator-profile-lane" aria-label="Permalink to &quot;Orchestrator profile lane&quot;">​</a></h3><p>Orchestrator 是特殊的 profile lane。</p><p>它的职责不是自己执行任务，而是：</p><ul><li>拆解高层目标</li><li>创建子任务</li><li>设置 assignee</li><li>建立 parent / child links</li><li>然后退场</li></ul><p>更好的 orchestrator 应该有 <code>kanban</code> 能力，但不应该默认拥有 <code>terminal</code>、<code>file</code>、<code>code</code>、<code>web</code> 这些执行工具。</p><p>它是控制室，不是万能工人。</p><h3 id="外部-cli-worker-lane" tabindex="-1">外部 CLI worker lane <a class="header-anchor" href="#外部-cli-worker-lane" aria-label="Permalink to &quot;外部 CLI worker lane&quot;">​</a></h3><p>文档也提到可以接入非 Hermes worker，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Codex CLI</span></span>
<span class="line"><span>Claude Code CLI</span></span>
<span class="line"><span>OpenCode CLI</span></span>
<span class="line"><span>本地 coding model runner</span></span></code></pre></div><p>但这还不是完全铺好的路径。</p><p>外部 lane 需要解决：</p><ul><li>如何启动外部 CLI</li><li>如何把退出码映射到 <code>kanban_complete</code> / <code>kanban_block</code></li><li>如何处理 workspace / sandbox</li><li>如何处理认证和策略</li><li>如何把日志、结果和错误写回 Kanban</li></ul><p>所以它更像插件集成问题，不是 Kanban kernel 的默认能力。</p><h2 id="dispatcher-处理的失败模式" tabindex="-1">dispatcher 处理的失败模式 <a class="header-anchor" href="#dispatcher-处理的失败模式" aria-label="Permalink to &quot;dispatcher 处理的失败模式&quot;">​</a></h2><p>worker lane 作者不需要自己重做所有失败恢复，因为 dispatcher 已经负责一些通用情况：</p><h3 id="stale-claim-ttl" tabindex="-1">Stale claim TTL <a class="header-anchor" href="#stale-claim-ttl" aria-label="Permalink to &quot;Stale claim TTL&quot;">​</a></h3><p>worker claim 了任务，但之后没有完成、没有 block、也没有有效 heartbeat。</p><p>超过 TTL 后，任务可以被回收。</p><h3 id="crashed-worker" tabindex="-1">Crashed worker <a class="header-anchor" href="#crashed-worker" aria-label="Permalink to &quot;Crashed worker&quot;">​</a></h3><p>如果本机 PID 消失，说明 worker 进程可能崩溃。</p><p>dispatcher 会回收任务，并增加失败计数。</p><h3 id="run-level-retry" tabindex="-1">Run-level retry <a class="header-anchor" href="#run-level-retry" aria-label="Permalink to &quot;Run-level retry&quot;">​</a></h3><p>同一张任务卡可以有多次 run。</p><p>如果任务被重试，worker 可以通过 run id / expected run id 判断自己是不是已经过期，避免旧 worker 覆盖新 worker 结果。</p><h3 id="per-task-max-runtime" tabindex="-1">Per-task max runtime <a class="header-anchor" href="#per-task-max-runtime" aria-label="Permalink to &quot;Per-task max runtime&quot;">​</a></h3><p>任务可以设置最大运行时间。</p><p>即使 PID 还活着，如果超过 wall-clock 限制，也可以被判定为超时。</p><h3 id="stranded-task-detection" tabindex="-1">Stranded task detection <a class="header-anchor" href="#stranded-task-detection" aria-label="Permalink to &quot;Stranded task detection&quot;">​</a></h3><p>如果任务一直停在 <code>ready</code>，但 assignee 从不 claim，说明可能有问题：</p><ul><li>assignee 拼错</li><li>profile 被删了</li><li>外部 worker pool 不在线</li></ul><p>诊断工具会把它标成 stranded。</p><h2 id="我的理解" tabindex="-1">我的理解 <a class="header-anchor" href="#我的理解" aria-label="Permalink to &quot;我的理解&quot;">​</a></h2><p>Worker lane 解决的是“任务卡如何变成一个实际执行过程”的问题。</p><p>它把执行者抽象成一个可替换通道：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>任务卡 -&gt; assignee -&gt; lane -&gt; spawn worker -&gt; worker 回写结果</span></span></code></pre></div><p>关键不是“怎么启动某个进程”，而是启动后必须遵守同一套生命周期契约：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>show -&gt; work -&gt; heartbeat -&gt; complete / block</span></span></code></pre></div><p>这样无论 worker 是 Hermes profile、外部 CLI，还是未来的容器服务，都能通过同一套 Kanban 状态机协作。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/hermes/kanban/Worker Lane 与任务执行.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Worker_Lane______ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Worker_Lane______ as default
};
