import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Kanban 使用场景","description":"","frontmatter":{},"headers":[],"relativePath":"projects/hermes/kanban/Kanban 使用场景.md","filePath":"projects/hermes/kanban/Kanban 使用场景.md"}');
const _sfc_main = { name: "projects/hermes/kanban/Kanban 使用场景.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="kanban-使用场景" tabindex="-1">Kanban 使用场景 <a class="header-anchor" href="#kanban-使用场景" aria-label="Permalink to &quot;Kanban 使用场景&quot;">​</a></h1><p>这篇笔记整理自 <code>kanban-tutorial.md</code>，主要记录 Hermes Kanban 适合哪些场景，以及每种场景想说明什么机制。</p><h2 id="教程的前提" tabindex="-1">教程的前提 <a class="header-anchor" href="#教程的前提" aria-label="Permalink to &quot;教程的前提&quot;">​</a></h2><p>教程假设你已经知道几个基础概念：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>task        任务卡</span></span>
<span class="line"><span>run         一次执行尝试</span></span>
<span class="line"><span>assignee    分配给哪个 profile</span></span>
<span class="line"><span>dispatcher  扫描看板并启动 worker 的调度器</span></span></code></pre></div><p>用户可以通过 dashboard / CLI 查看和操作任务；worker 不看 dashboard，也不跑 CLI，而是通过 <code>kanban_*</code> 工具读写看板。</p><h2 id="看板列" tabindex="-1">看板列 <a class="header-anchor" href="#看板列" aria-label="Permalink to &quot;看板列&quot;">​</a></h2><p>Dashboard 里常见列：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Triage       粗略想法，等待拆解或明确</span></span>
<span class="line"><span>Todo         已创建，但还没满足依赖或还没分配</span></span>
<span class="line"><span>Ready        已分配，等待 dispatcher claim</span></span>
<span class="line"><span>In progress  worker 正在执行</span></span>
<span class="line"><span>Blocked      等待人类输入，或失败熔断</span></span>
<span class="line"><span>Done         已完成</span></span></code></pre></div><p>这套列就是任务状态机的可视化。</p><h2 id="场景一-单人开发一个-feature" tabindex="-1">场景一：单人开发一个 feature <a class="header-anchor" href="#场景一-单人开发一个-feature" aria-label="Permalink to &quot;场景一：单人开发一个 feature&quot;">​</a></h2><p>经典流程：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Design schema -&gt; Implement API -&gt; Write tests</span></span></code></pre></div><p>这说明 Kanban 如何表达任务依赖。</p><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>SCHEMA -&gt; API -&gt; TESTS</span></span></code></pre></div><p>只有 <code>SCHEMA</code> 一开始是 <code>ready</code>。<code>API</code> 和 <code>TESTS</code> 会停在 <code>todo</code>，直到父任务完成。</p><p>worker 完成 <code>SCHEMA</code> 后，会写入：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>summary</span></span>
<span class="line"><span>metadata</span></span></code></pre></div><p>下游 <code>API</code> worker 调用 <code>kanban_show()</code> 时，就能看到父任务的结构化结果，而不需要重新读一篇长设计文档。</p><p>这个场景的重点：</p><blockquote><p>Kanban 不只是任务列表，它能把上游产出作为下游 worker 的上下文交接。</p></blockquote><h2 id="场景二-fleet-farming" tabindex="-1">场景二：Fleet farming <a class="header-anchor" href="#场景二-fleet-farming" aria-label="Permalink to &quot;场景二：Fleet farming&quot;">​</a></h2><p>Fleet farming 指一个或多个 specialist profile 并行处理大量独立任务。</p><p>例子：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>translator   翻译多个页面</span></span>
<span class="line"><span>transcriber  转写多个通话</span></span>
<span class="line"><span>copywriter   写多个商品描述</span></span></code></pre></div><p>这些任务彼此没有依赖，可以并行执行。</p><p>dispatcher 会根据 assignee 把任务分配给对应 profile。Dashboard 的 <code>In progress</code> 可以按 profile 分 lane 展示，让用户看到每个 worker 正在做什么。</p><p>这个场景的重点：</p><blockquote><p>Kanban 可以把一堆同类或独立任务交给多个 specialist profile 并行消化，同时保留可见进度和结构化结果。</p></blockquote><h2 id="场景三-角色流水线-重试" tabindex="-1">场景三：角色流水线 + 重试 <a class="header-anchor" href="#场景三-角色流水线-重试" aria-label="Permalink to &quot;场景三：角色流水线 + 重试&quot;">​</a></h2><p>这是 Kanban 比普通 TODO list 更有价值的地方。</p><p>示例流程：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PM 写规格 -&gt; Engineer 实现 -&gt; Reviewer 审查 -&gt; Engineer 修改 -&gt; Reviewer 通过</span></span></code></pre></div><p>关键是：某个任务可能不是一次成功。</p><p>例如实现任务第一次被 reviewer 打回：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>run 1 -&gt; blocked</span></span>
<span class="line"><span>reason = password strength check missing ...</span></span></code></pre></div><p>人类或 reviewer unblock 后，同一张任务卡会产生第二次 run：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>run 2 -&gt; completed</span></span>
<span class="line"><span>metadata = changed_files / tests_run / review_iteration</span></span></code></pre></div><p>第二次 worker 读取任务时，会看到第一次 block 的原因，因此不需要从头猜问题。</p><p>这个场景的重点：</p><blockquote><p>Kanban 的 retry history 是一等结构。失败、阻塞、修改、再次完成，都保存在同一张任务卡的 run history 里。</p></blockquote><h2 id="场景四-熔断和崩溃恢复" tabindex="-1">场景四：熔断和崩溃恢复 <a class="header-anchor" href="#场景四-熔断和崩溃恢复" aria-label="Permalink to &quot;场景四：熔断和崩溃恢复&quot;">​</a></h2><p>真实 worker 会失败，例如：</p><ul><li>缺少环境变量</li><li>认证失败</li><li>OOM</li><li>进程崩溃</li><li>网络问题</li><li>外部 CLI 不存在</li></ul><p>Kanban 有两类防护：</p><h3 id="circuit-breaker" tabindex="-1">Circuit breaker <a class="header-anchor" href="#circuit-breaker" aria-label="Permalink to &quot;Circuit breaker&quot;">​</a></h3><p>如果某个任务连续失败太多次，dispatcher 不会无限重试，而是把任务自动 block。</p><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>spawn_failed</span></span>
<span class="line"><span>spawn_failed</span></span>
<span class="line"><span>gave_up</span></span></code></pre></div><p>这样坏任务不会无限消耗 worker。</p><h3 id="crash-recovery" tabindex="-1">Crash recovery <a class="header-anchor" href="#crash-recovery" aria-label="Permalink to &quot;Crash recovery&quot;">​</a></h3><p>如果 worker 已经启动，但中途进程死掉，dispatcher 可以检测到 PID 消失，然后释放 claim，让任务回到 <code>ready</code>，下一轮重新调度。</p><p>重试 worker 可以看到之前 run 的失败原因，选择不同策略继续执行。</p><p>这个场景的重点：</p><blockquote><p>Kanban 把失败当成正常状态来建模，而不是把失败藏在某次对话上下文里。</p></blockquote><h2 id="结构化交接为什么重要" tabindex="-1">结构化交接为什么重要 <a class="header-anchor" href="#结构化交接为什么重要" aria-label="Permalink to &quot;结构化交接为什么重要&quot;">​</a></h2><p>教程反复强调 <code>summary</code> 和 <code>metadata</code>。</p><p>worker 完成任务时，不应该只写一句“完成了”，而应该写清楚：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>summary   人类可读的结果</span></span>
<span class="line"><span>metadata  机器可读的结构化信息</span></span></code></pre></div><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>changed_files</span></span>
<span class="line"><span>tests_run</span></span>
<span class="line"><span>decisions</span></span>
<span class="line"><span>acceptance</span></span>
<span class="line"><span>review_iteration</span></span></code></pre></div><p>这样下游 worker / reviewer 可以快速知道：</p><ul><li>上游做了什么</li><li>怎么验证的</li><li>哪些文件改了</li><li>哪些风险还在</li><li>之前为什么失败</li></ul><h2 id="运行中任务如何查看" tabindex="-1">运行中任务如何查看 <a class="header-anchor" href="#运行中任务如何查看" aria-label="Permalink to &quot;运行中任务如何查看&quot;">​</a></h2><p>一个任务在 <code>running</code> 时，会有一个 active run。</p><p>如果 worker 后续：</p><ul><li>完成，run 变成 <code>completed</code></li><li>block，run 变成 <code>blocked</code></li><li>崩溃，run 变成 <code>crashed</code></li><li>超时，run 变成 <code>timed_out</code></li></ul><p>run 不会消失，而是变成 attempt history 的一部分。</p><p>这让用户能复盘整个任务经历了什么，而不只是看到最新状态。</p><h2 id="我的理解" tabindex="-1">我的理解 <a class="header-anchor" href="#我的理解" aria-label="Permalink to &quot;我的理解&quot;">​</a></h2><p><code>kanban-tutorial.md</code> 的重点不是教几个命令，而是用场景证明 Kanban 的几个能力：</p><ul><li>任务依赖：父任务完成后子任务才 ready。</li><li>并行处理：多个 profile 可以同时消化任务。</li><li>角色流水线：不同 profile 按阶段接力。</li><li>阻塞重试：block / unblock 让人类介入成为一等流程。</li><li>崩溃恢复：worker 死掉后任务不会丢。</li><li>结构化交接：summary / metadata 让下游 worker 不用猜。</li></ul><p>一句话：</p><blockquote><p>Kanban 的价值在于把多 Agent 协作中的“过程”也保存下来，而不只是保存最终结果。</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/hermes/kanban/Kanban 使用场景.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Kanban_____ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Kanban_____ as default
};
