import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Hermes Kanban 核心概念","description":"","frontmatter":{},"headers":[],"relativePath":"projects/hermes/kanban/Hermes Kanban 核心概念.md","filePath":"projects/hermes/kanban/Hermes Kanban 核心概念.md"}');
const _sfc_main = { name: "projects/hermes/kanban/Hermes Kanban 核心概念.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="hermes-kanban-核心概念" tabindex="-1">Hermes Kanban 核心概念 <a class="header-anchor" href="#hermes-kanban-核心概念" aria-label="Permalink to &quot;Hermes Kanban 核心概念&quot;">​</a></h1><p>这篇笔记整理自 <code>kanban.md</code>，目标是快速抓住 Hermes Kanban 的核心机制，而不是逐字翻译原文。</p><h2 id="一句话理解" tabindex="-1">一句话理解 <a class="header-anchor" href="#一句话理解" aria-label="Permalink to &quot;一句话理解&quot;">​</a></h2><p>Hermes Kanban 是一个基于 SQLite 的持久化任务看板，用来协调多个 Hermes profile / Agent 协作。</p><p>它解决的问题是：多个 Agent 不再依赖脆弱的进程内子 Agent 调用，而是通过同一个任务看板交接工作、记录状态、恢复失败和审计过程。</p><p>可以理解成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>任务卡 = 工作单元</span></span>
<span class="line"><span>看板 = 多 Agent 之间的共享状态层</span></span>
<span class="line"><span>dispatcher = 扫描看板并启动 worker 的调度器</span></span>
<span class="line"><span>profile = 具体执行任务的 Agent 身份</span></span></code></pre></div><h2 id="两种操作入口" tabindex="-1">两种操作入口 <a class="header-anchor" href="#两种操作入口" aria-label="Permalink to &quot;两种操作入口&quot;">​</a></h2><p>Hermes Kanban 有两类入口：</p><ol><li><strong>人类 / 脚本入口</strong></li></ol><p>用户通过这些方式操作看板：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>hermes kanban ...</span></span>
<span class="line"><span>/kanban ...</span></span>
<span class="line"><span>dashboard</span></span>
<span class="line"><span>cron / scripts</span></span></code></pre></div><p>这些入口适合创建任务、查看状态、评论、解除阻塞、归档等。</p><ol start="2"><li><strong>Agent / worker 入口</strong></li></ol><p>Agent 不应该在任务执行时 shell 调用 <code>hermes kanban</code>，而是通过 <code>kanban_*</code> 工具直接读写看板，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>kanban_show</span></span>
<span class="line"><span>kanban_complete</span></span>
<span class="line"><span>kanban_block</span></span>
<span class="line"><span>kanban_heartbeat</span></span>
<span class="line"><span>kanban_comment</span></span>
<span class="line"><span>kanban_create</span></span>
<span class="line"><span>kanban_link</span></span>
<span class="line"><span>kanban_unblock</span></span></code></pre></div><p>这样可以避免 shell 参数转义问题，也能让工具结果保持结构化。</p><h2 id="kanban-和-delegate-task-的区别" tabindex="-1">Kanban 和 delegate_task 的区别 <a class="header-anchor" href="#kanban-和-delegate-task-的区别" aria-label="Permalink to &quot;Kanban 和 delegate_task 的区别&quot;">​</a></h2><p><code>delegate_task</code> 和 Kanban 都能让 Agent 把工作交给另一个执行者，但它们不是同一种机制。</p><table tabindex="0"><thead><tr><th>对比项</th><th>delegate_task</th><th>Kanban</th></tr></thead><tbody><tr><td>形态</td><td>一次 RPC 调用</td><td>持久化任务队列 + 状态机</td></tr><tr><td>父 Agent</td><td>等子任务返回</td><td>创建任务后可以结束</td></tr><tr><td>子 Agent 身份</td><td>匿名、短生命周期</td><td>命名 profile，有自己的 memory / skills</td></tr><tr><td>可恢复性</td><td>失败就失败</td><td>可 block / unblock / reclaim / retry</td></tr><tr><td>人类介入</td><td>不适合</td><td>可以 comment / unblock / reassign</td></tr><tr><td>审计记录</td><td>容易随上下文压缩丢失</td><td>SQLite 中长期保存</td></tr></tbody></table><p>一句话：</p><blockquote><p><code>delegate_task</code> 是函数调用；Kanban 是一个持久化工作队列，每次交接都是任何 profile 或人类都能读写的一行记录。</p></blockquote><p>适合用 <code>delegate_task</code> 的情况：</p><ul><li>短小、自包含的推理任务</li><li>父 Agent 需要立刻拿到答案继续执行</li><li>不需要人类介入</li><li>不需要长期审计</li></ul><p>适合用 Kanban 的情况：</p><ul><li>工作跨多个 Agent / profile</li><li>任务需要跨进程、跨轮次存在</li><li>可能需要人类输入</li><li>可能需要失败恢复或重试</li><li>结果以后还要被追踪和审计</li></ul><h2 id="核心概念" tabindex="-1">核心概念 <a class="header-anchor" href="#核心概念" aria-label="Permalink to &quot;核心概念&quot;">​</a></h2><h3 id="board" tabindex="-1">Board <a class="header-anchor" href="#board" aria-label="Permalink to &quot;Board&quot;">​</a></h3><p>Board 是一个独立任务队列，有自己的 SQLite DB、workspace 目录和 dispatcher loop。</p><p>一个 Hermes 安装可以有多个 board，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>default</span></span>
<span class="line"><span>project-a</span></span>
<span class="line"><span>repo-x</span></span>
<span class="line"><span>ops</span></span></code></pre></div><p>不同 board 之间隔离：</p><ul><li>SQLite DB 独立</li><li>workspace / logs 独立</li><li>worker 只能看到自己 board 的任务</li><li>不允许跨 board 建 task link</li></ul><h3 id="task" tabindex="-1">Task <a class="header-anchor" href="#task" aria-label="Permalink to &quot;Task&quot;">​</a></h3><p>Task 是任务卡，是看板里的基本工作单元。</p><p>它通常包含：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>title</span></span>
<span class="line"><span>body</span></span>
<span class="line"><span>assignee</span></span>
<span class="line"><span>status</span></span>
<span class="line"><span>tenant</span></span>
<span class="line"><span>workspace</span></span>
<span class="line"><span>priority</span></span>
<span class="line"><span>idempotency key</span></span></code></pre></div><p>常见状态：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>triage    粗略想法，等待拆解或明确</span></span>
<span class="line"><span>todo      已创建，但依赖还没满足或还没准备好</span></span>
<span class="line"><span>ready     可以被 dispatcher 领取</span></span>
<span class="line"><span>running   worker 正在执行</span></span>
<span class="line"><span>blocked   等待人类或其他 profile 输入</span></span>
<span class="line"><span>done      已完成</span></span>
<span class="line"><span>archived  已归档</span></span></code></pre></div><h3 id="link" tabindex="-1">Link <a class="header-anchor" href="#link" aria-label="Permalink to &quot;Link&quot;">​</a></h3><p>Link 表示任务依赖关系。</p><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Research -&gt; Draft -&gt; Review</span></span></code></pre></div><p>后一个任务必须等前一个任务完成后才会从 <code>todo</code> 推进到 <code>ready</code>。</p><p>这让 Kanban 可以表达流水线、fan-in、fan-out 等协作结构。</p><h3 id="comment" tabindex="-1">Comment <a class="header-anchor" href="#comment" aria-label="Permalink to &quot;Comment&quot;">​</a></h3><p>Comment 是 Agent 和人类之间的持久化交流通道。</p><p>它可以记录：</p><ul><li>问题</li><li>人类反馈</li><li>中间产物</li><li>审查意见</li><li>重试原因</li><li>后续建议</li></ul><p>worker 被重新启动时，会读取完整 comment thread。因此不需要依赖脆弱的聊天上下文。</p><h3 id="workspace" tabindex="-1">Workspace <a class="header-anchor" href="#workspace" aria-label="Permalink to &quot;Workspace&quot;">​</a></h3><p>Workspace 是 worker 执行任务时所在的目录。</p><p>主要有三种：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>scratch        临时目录，任务完成后可清理</span></span>
<span class="line"><span>dir:&lt;path&gt;     指向已有目录，例如 Obsidian vault、项目目录、邮件处理目录</span></span>
<span class="line"><span>worktree       git worktree，适合代码任务</span></span></code></pre></div><p>Workspace 的意义是给任务一个明确的文件上下文边界，避免多个 worker 混在同一个目录里互相影响。</p><h3 id="dispatcher" tabindex="-1">Dispatcher <a class="header-anchor" href="#dispatcher" aria-label="Permalink to &quot;Dispatcher&quot;">​</a></h3><p>Dispatcher 是调度器，默认跑在 gateway 里。</p><p>它做的事主要是：</p><ol><li>扫描任务状态。</li><li>把依赖已满足的任务推进到 <code>ready</code>。</li><li>原子 claim 一个 <code>ready</code> 任务。</li><li>根据 <code>assignee</code> 启动对应 profile。</li><li>回收 stale claim 或崩溃 worker。</li><li>连续失败后自动 block，避免无限重试。</li></ol><p>Dispatcher 不应该做复杂智能路由。智能路由、预算、审批、组织层级更适合放到 profile、skill 或 plugin。</p><h3 id="tenant" tabindex="-1">Tenant <a class="header-anchor" href="#tenant" aria-label="Permalink to &quot;Tenant&quot;">​</a></h3><p>Tenant 是 board 内的可选命名空间。</p><p>它适合一个 specialist fleet 服务多个业务上下文：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>business-a</span></span>
<span class="line"><span>business-b</span></span>
<span class="line"><span>personal</span></span></code></pre></div><p>Tenant 不是强隔离边界，更像软过滤和上下文标签。真正的硬隔离还是 board。</p><h2 id="worker-如何执行任务" tabindex="-1">Worker 如何执行任务 <a class="header-anchor" href="#worker-如何执行任务" aria-label="Permalink to &quot;Worker 如何执行任务&quot;">​</a></h2><p>一个典型 worker 流程是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>dispatcher claim task</span></span>
<span class="line"><span>dispatcher spawn profile</span></span>
<span class="line"><span>worker 调用 kanban_show 读取任务上下文</span></span>
<span class="line"><span>worker 在 workspace 中做实际工作</span></span>
<span class="line"><span>worker 定期 kanban_heartbeat</span></span>
<span class="line"><span>worker 完成后 kanban_complete</span></span>
<span class="line"><span>如果卡住，则 kanban_block</span></span></code></pre></div><p>其中 <code>kanban_complete</code> 最好写清楚：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>summary     人类可读的结果摘要</span></span>
<span class="line"><span>metadata    结构化交接信息，例如 changed_files、verification、residual_risk</span></span></code></pre></div><p>这样下游任务或 reviewer 不需要重新猜测上游做了什么。</p><h2 id="为什么用工具而不是-cli" tabindex="-1">为什么用工具而不是 CLI <a class="header-anchor" href="#为什么用工具而不是-cli" aria-label="Permalink to &quot;为什么用工具而不是 CLI&quot;">​</a></h2><p>worker 用 <code>kanban_*</code> 工具有几个好处：</p><ol><li><strong>避免环境问题</strong>：如果 worker 的 terminal 在 Docker / SSH / Modal 里，里面不一定有 <code>hermes</code> 命令或本地 DB。</li><li><strong>避免 shell 转义问题</strong>：结构化 metadata 不需要被塞进命令行字符串。</li><li><strong>错误更清楚</strong>：工具返回结构化 JSON，模型更容易理解。</li><li><strong>正常会话不膨胀</strong>：普通 <code>hermes chat</code> 不会默认带上所有 <code>kanban_*</code> 工具。</li></ol><h2 id="dashboard-的作用" tabindex="-1">Dashboard 的作用 <a class="header-anchor" href="#dashboard-的作用" aria-label="Permalink to &quot;Dashboard 的作用&quot;">​</a></h2><p>Dashboard 不是核心逻辑，只是人类更舒服地看和操作 Kanban 的界面。</p><p>它适合：</p><ul><li>查看任务状态</li><li>看 comment thread</li><li>拖动任务状态</li><li>批量 reassign / archive</li><li>查看 run history</li><li>看 worker 日志和事件</li></ul><p>它本质上仍然通过同一个 <code>kanban_db</code> 层读写 SQLite，所以 CLI、Dashboard、Agent 工具不会各自维护一套状态。</p><h2 id="runs-和-events" tabindex="-1">Runs 和 Events <a class="header-anchor" href="#runs-和-events" aria-label="Permalink to &quot;Runs 和 Events&quot;">​</a></h2><p>Task 是逻辑工作单元，Run 是一次执行尝试。</p><p>一个任务可能经历多次 run：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>run 1 blocked</span></span>
<span class="line"><span>run 2 crashed</span></span>
<span class="line"><span>run 3 completed</span></span></code></pre></div><p>Run 用来保存每次尝试的：</p><ul><li>worker profile</li><li>started / ended</li><li>outcome</li><li>summary</li><li>metadata</li><li>error</li><li>log path</li></ul><p>Event 则记录状态变化和执行过程，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>created</span></span>
<span class="line"><span>promoted</span></span>
<span class="line"><span>claimed</span></span>
<span class="line"><span>spawned</span></span>
<span class="line"><span>heartbeat</span></span>
<span class="line"><span>completed</span></span>
<span class="line"><span>blocked</span></span>
<span class="line"><span>unblocked</span></span>
<span class="line"><span>crashed</span></span>
<span class="line"><span>timed_out</span></span>
<span class="line"><span>stale</span></span>
<span class="line"><span>gave_up</span></span></code></pre></div><p>Runs 解决“尝试历史”，Events 解决“时间线审计”。</p><h2 id="典型协作模式" tabindex="-1">典型协作模式 <a class="header-anchor" href="#典型协作模式" aria-label="Permalink to &quot;典型协作模式&quot;">​</a></h2><p>Kanban 支持一些常见协作模式：</p><ul><li><strong>Fan-out</strong>：一个任务拆成多个并行子任务。</li><li><strong>Pipeline</strong>：Research -&gt; Draft -&gt; Review 这种顺序链条。</li><li><strong>Voting / Quorum</strong>：多个 worker 给答案，一个 aggregator 汇总。</li><li><strong>Long-running journal</strong>：同一个 profile 定期写入同一个 workspace。</li><li><strong>Human-in-the-loop</strong>：worker block，用户 comment，然后 unblock。</li><li><strong>@mention delegation</strong>：通过 <code>@reviewer</code> 这种方式创建委派任务。</li><li><strong>Thread-scoped workspace</strong>：聊天 thread 绑定 workspace。</li><li><strong>Fleet farming</strong>：一个 specialist profile 管很多相似对象。</li></ul><p>这些模式本质上都来自同一组原语：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>tasks + links + comments + assignee + workspace</span></span></code></pre></div><h2 id="适用边界" tabindex="-1">适用边界 <a class="header-anchor" href="#适用边界" aria-label="Permalink to &quot;适用边界&quot;">​</a></h2><p>Kanban 设计上偏单机。</p><p>它假设：</p><ul><li><code>kanban.db</code> 是本地 SQLite 文件。</li><li>dispatcher 在同一台机器上启动 worker。</li><li>crash detection 可以通过本机 PID 判断。</li></ul><p>如果要跨多主机协作，Kanban 本身不是完整方案，需要额外的消息队列、远程调度或每台机器独立 board。</p><h2 id="我的理解" tabindex="-1">我的理解 <a class="header-anchor" href="#我的理解" aria-label="Permalink to &quot;我的理解&quot;">​</a></h2><p>Hermes Kanban 的关键不是“多开几个 Agent”，而是把多 Agent 协作变成一个可持久化、可恢复、可审计的工作流系统。</p><p>它最重要的设计取舍是：</p><ul><li>用 SQLite 做共享状态，而不是让 Agent 彼此直接通信。</li><li>用 profile 表示 worker 身份，而不是重新发明 agent entity。</li><li>用 task / link / comment / event 表达协作，而不是设计复杂协议。</li><li>用 dispatcher 做简单调度，把智能路由留给 profile / skill / plugin。</li><li>用 run / event 保存尝试历史和审计线索。</li></ul><p>一句话总结：</p><blockquote><p>Kanban 是 Hermes 的多 Agent 协作状态层；它让任务、交接、失败恢复和人类介入都变成可记录、可恢复的结构化流程。</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/hermes/kanban/Hermes Kanban 核心概念.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Hermes_Kanban_____ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Hermes_Kanban_____ as default
};
