import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Heartbeat / TTL / Worker 健康检查","description":"","frontmatter":{},"headers":[],"relativePath":"projects/hermes/kanban/Worker 心跳与任务租约.md","filePath":"projects/hermes/kanban/Worker 心跳与任务租约.md"}');
const _sfc_main = { name: "projects/hermes/kanban/Worker 心跳与任务租约.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="heartbeat-ttl-worker-健康检查" tabindex="-1">Heartbeat / TTL / Worker 健康检查 <a class="header-anchor" href="#heartbeat-ttl-worker-健康检查" aria-label="Permalink to &quot;Heartbeat / TTL / Worker 健康检查&quot;">​</a></h1><h2 id="_1-heartbeat-是什么" tabindex="-1">1. Heartbeat 是什么 <a class="header-anchor" href="#_1-heartbeat-是什么" aria-label="Permalink to &quot;1. Heartbeat 是什么&quot;">​</a></h2><p><strong>Heartbeat，心跳机制，就是 worker 定期向系统报平安：我还活着，而且我还在处理这个任务。</strong></p><p>在任务系统里，一个 worker 被调度器启动后，会把任务从 <code>ready</code> 改成 <code>running</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>task T123 -&gt; running</span></span>
<span class="line"><span>worker process started</span></span></code></pre></div><p>但系统不能只知道“这个 worker 被启动了”，还要知道它后面是不是仍然正常工作。</p><p>所以 worker 会定期更新：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>tasks.last_heartbeat_at = 当前时间</span></span>
<span class="line"><span>task_runs.last_heartbeat_at = 当前时间</span></span>
<span class="line"><span>task_events 记录 heartbeat event</span></span></code></pre></div><p>意思是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我还活着</span></span>
<span class="line"><span>我还能访问任务系统</span></span>
<span class="line"><span>我还没有彻底失联</span></span></code></pre></div><hr><h2 id="_2-pid-liveness-和-heartbeat-的区别" tabindex="-1">2. PID liveness 和 heartbeat 的区别 <a class="header-anchor" href="#_2-pid-liveness-和-heartbeat-的区别" aria-label="Permalink to &quot;2. PID liveness 和 heartbeat 的区别&quot;">​</a></h2><p>系统通常可以看两种信号：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. PID liveness：进程还在不在</span></span>
<span class="line"><span>2. heartbeat：worker 有没有持续报活</span></span></code></pre></div><p>PID 是进程 ID。PID 还存在，只能说明：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>这个进程没有退出</span></span></code></pre></div><p>但不能说明：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>它真的还在推进任务</span></span>
<span class="line"><span>它没有卡死</span></span>
<span class="line"><span>它没有死循环</span></span>
<span class="line"><span>它没有阻塞在 IO / 网络请求上</span></span>
<span class="line"><span>它还能访问数据库或任务系统</span></span></code></pre></div><p>所以：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PID liveness = 进程层面的“还活着”</span></span>
<span class="line"><span>Heartbeat = 应用层面的“还能正常报活”</span></span></code></pre></div><p>两者互补：</p><table tabindex="0"><thead><tr><th>情况</th><th>说明</th></tr></thead><tbody><tr><td>PID 存在，heartbeat 正常</td><td>大概率还在正常执行</td></tr><tr><td>PID 存在，heartbeat 很久没更新</td><td>进程可能假死、卡住、死循环或无法访问任务系统</td></tr><tr><td>PID 不存在，heartbeat 停止</td><td>worker 大概率已经退出或崩溃</td></tr><tr><td>PID 不可检查，但 heartbeat 正常</td><td>可能是远程 worker / 容器 / 跨机器场景，心跳更可信</td></tr></tbody></table><p>一句话：</p><p><strong>PID 只能证明进程没死，heartbeat 才能证明 worker 还能和任务系统通信。</strong></p><hr><h2 id="_3-ttl-是什么" tabindex="-1">3. TTL 是什么 <a class="header-anchor" href="#_3-ttl-是什么" aria-label="Permalink to &quot;3. TTL 是什么&quot;">​</a></h2><p><strong>TTL 是 Time To Live，意思是“有效期”。</strong></p><p>比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>TTL = 5 分钟</span></span></code></pre></div><p>表示某个状态、缓存、token、锁、任务占用，最多只被认为有效 5 分钟。</p><p>在 worker 任务系统里，TTL 常用于任务认领：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>task.status = running</span></span>
<span class="line"><span>claim_lock = worker-123</span></span>
<span class="line"><span>claim_expires = 10:30</span></span></code></pre></div><p>意思是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>worker-123 对这个任务的占用权，只到 10:30 有效。</span></span></code></pre></div><p>如果到了 10:30，worker 还没有完成任务，也没有续约或心跳，调度器就可以认为：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>这个 worker 可能失联了</span></span>
<span class="line"><span>这个任务不能永久被它占着</span></span>
<span class="line"><span>应该释放出来重新调度</span></span></code></pre></div><p>所以 TTL 的作用是：</p><p><strong>防止资源、锁、任务被某个失联 worker 永久占用。</strong></p><hr><h2 id="_4-heartbeat-和-ttl-的关系" tabindex="-1">4. Heartbeat 和 TTL 的关系 <a class="header-anchor" href="#_4-heartbeat-和-ttl-的关系" aria-label="Permalink to &quot;4. Heartbeat 和 TTL 的关系&quot;">​</a></h2><p>Heartbeat 和 TTL 经常一起使用：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>heartbeat = worker 定期报活</span></span>
<span class="line"><span>TTL = 多久没报活就认为失联</span></span></code></pre></div><p>比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>heartbeat_interval = 30 秒</span></span>
<span class="line"><span>heartbeat_timeout = 2 分钟</span></span></code></pre></div><p>意思是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>worker 每 30 秒更新一次心跳</span></span>
<span class="line"><span>如果超过 2 分钟没有心跳，就认为 worker 可能失联</span></span></code></pre></div><p>调度器检查：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>now - last_heartbeat_at &gt; heartbeat_timeout</span></span></code></pre></div><p>如果成立，就可以把任务标记为 stale，然后回收：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>running -&gt; ready</span></span>
<span class="line"><span>清空 claim_lock</span></span>
<span class="line"><span>重新分发给其他 worker</span></span></code></pre></div><hr><h2 id="_5-lease-租约思想" tabindex="-1">5. Lease / 租约思想 <a class="header-anchor" href="#_5-lease-租约思想" aria-label="Permalink to &quot;5. Lease / 租约思想&quot;">​</a></h2><p>任务认领本质上不是永久拥有，而是一个 <strong>lease，租约</strong>。</p><p>worker 领取任务时：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我暂时拥有这个任务的执行权</span></span></code></pre></div><p>但这个执行权有过期时间：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>claim_expires = now + TTL</span></span></code></pre></div><p>worker 正常工作时，可以通过 heartbeat 或续约不断延长这个时间。</p><p>如果 worker 失联，不再续约，租约到期后任务会被释放。</p><p>所以更准确地说：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>worker 不是永久锁住任务</span></span>
<span class="line"><span>worker 只是持有一个会过期的任务租约</span></span></code></pre></div><p>这个设计可以避免：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>worker 崩溃后任务永远 running</span></span>
<span class="line"><span>任务被一个死进程永久占住</span></span>
<span class="line"><span>系统需要人工清理卡死任务</span></span></code></pre></div><hr><h2 id="_6-为什么要记录-heartbeat-event" tabindex="-1">6. 为什么要记录 heartbeat event <a class="header-anchor" href="#_6-为什么要记录-heartbeat-event" aria-label="Permalink to &quot;6. 为什么要记录 heartbeat event&quot;">​</a></h2><p>更新 <code>last_heartbeat_at</code> 只能看到当前状态。</p><p>记录 <code>heartbeat event</code> 可以看到历史轨迹：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>任务什么时候开始跑</span></span>
<span class="line"><span>中间有没有持续心跳</span></span>
<span class="line"><span>从什么时候开始没心跳</span></span>
<span class="line"><span>worker 是突然死了，还是慢慢卡住了</span></span>
<span class="line"><span>有没有频繁失联又恢复</span></span></code></pre></div><p>所以：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>last_heartbeat_at = 当前健康状态</span></span>
<span class="line"><span>heartbeat event = 历史审计与排查线索</span></span></code></pre></div><p>不过实际系统里，heartbeat event 可能不会每次都永久记录，否则日志会很多。可以选择：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>只更新 last_heartbeat_at</span></span>
<span class="line"><span>定期抽样记录 heartbeat event</span></span>
<span class="line"><span>只在状态变化时记录 event</span></span></code></pre></div><hr><h2 id="_7-需要注意误判" tabindex="-1">7. 需要注意误判 <a class="header-anchor" href="#_7-需要注意误判" aria-label="Permalink to &quot;7. 需要注意误判&quot;">​</a></h2><p>Heartbeat 不是绝对可靠的。</p><p>可能出现：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>worker 还在正常工作，但数据库短暂不可用，导致心跳失败</span></span>
<span class="line"><span>worker 正在执行一个很长的阻塞操作，没来得及打心跳</span></span>
<span class="line"><span>网络抖动导致心跳延迟</span></span>
<span class="line"><span>GC / CPU 卡顿导致心跳晚到</span></span></code></pre></div><p>所以 heartbeat timeout 不能设置得太短。</p><p>通常会设计成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>heartbeat_interval 比较短</span></span>
<span class="line"><span>heartbeat_timeout 是 interval 的几倍</span></span></code></pre></div><p>比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>每 30 秒心跳一次</span></span>
<span class="line"><span>超过 2～5 分钟没心跳才判定失联</span></span></code></pre></div><p>这样可以减少误杀正常 worker。</p><hr><h2 id="_8-回收任务时要考虑幂等" tabindex="-1">8. 回收任务时要考虑幂等 <a class="header-anchor" href="#_8-回收任务时要考虑幂等" aria-label="Permalink to &quot;8. 回收任务时要考虑幂等&quot;">​</a></h2><p>如果 worker 被误判失联，任务被重新派发，但原 worker 后来又恢复了，就可能出现：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>两个 worker 同时执行同一个任务</span></span></code></pre></div><p>所以任务系统通常还要考虑：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>幂等性</span></span>
<span class="line"><span>重复执行保护</span></span>
<span class="line"><span>结果提交时检查 claim_lock</span></span>
<span class="line"><span>只允许当前 claim owner complete</span></span>
<span class="line"><span>使用 run_id 区分每次执行</span></span></code></pre></div><p>例如 worker 完成任务时，不能只写：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>complete task T123</span></span></code></pre></div><p>最好检查：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>只有 claim_lock 仍然属于自己</span></span>
<span class="line"><span>或者 run_id 仍然匹配</span></span>
<span class="line"><span>才能把任务改成 done</span></span></code></pre></div><p>否则旧 worker 可能覆盖新 worker 的结果。</p><hr><h2 id="_9-重试上限和-dead-letter" tabindex="-1">9. 重试上限和 Dead Letter <a class="header-anchor" href="#_9-重试上限和-dead-letter" aria-label="Permalink to &quot;9. 重试上限和 Dead Letter&quot;">​</a></h2><p>如果一个任务总是失败或总是超时，不能无限重试。</p><p>通常会加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>retry_count</span></span>
<span class="line"><span>max_retries</span></span>
<span class="line"><span>last_error</span></span>
<span class="line"><span>dead_letter / failed 状态</span></span></code></pre></div><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>任务超时 -&gt; 重新 ready</span></span>
<span class="line"><span>再次超时 -&gt; retry_count + 1</span></span>
<span class="line"><span>超过 max_retries -&gt; failed / dead_letter</span></span></code></pre></div><p>这样可以避免坏任务无限消耗 worker。</p><p>Dead Letter 的意思是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>这个任务已经多次失败，不再自动重试，交给人工排查。</span></span></code></pre></div><hr><h2 id="_10-和生产者-消费者模型的关系" tabindex="-1">10. 和生产者-消费者模型的关系 <a class="header-anchor" href="#_10-和生产者-消费者模型的关系" aria-label="Permalink to &quot;10. 和生产者-消费者模型的关系&quot;">​</a></h2><p>这个机制常见于生产者-消费者架构：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>生产者：创建任务</span></span>
<span class="line"><span>队列：保存任务</span></span>
<span class="line"><span>消费者：领取任务并执行</span></span>
<span class="line"><span>心跳：消费者定期报活</span></span>
<span class="line"><span>TTL：消费者多久没报活就算失联</span></span>
<span class="line"><span>回收：失联后释放任务，重新派发</span></span></code></pre></div><p>对应到 agent 系统：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>生产者 = 用户 / orchestrator / scheduler</span></span>
<span class="line"><span>队列 = tasks 表 / kanban board</span></span>
<span class="line"><span>消费者 = worker / agent process</span></span>
<span class="line"><span>健康检查 = PID liveness + heartbeat</span></span>
<span class="line"><span>恢复机制 = TTL 到期后 reclaim</span></span></code></pre></div><hr><h2 id="_11-常见场景" tabindex="-1">11. 常见场景 <a class="header-anchor" href="#_11-常见场景" aria-label="Permalink to &quot;11. 常见场景&quot;">​</a></h2><p>Heartbeat / TTL 是非常常见的工程模式，常见于：</p><table tabindex="0"><thead><tr><th>场景</th><th>用途</th></tr></thead><tbody><tr><td>任务队列 worker</td><td>判断任务消费者是否卡死</td></tr><tr><td>分布式锁</td><td>锁过期自动释放</td></tr><tr><td>Kubernetes</td><td>检查容器是否健康</td></tr><tr><td>WebSocket</td><td>判断连接是否还活着</td></tr><tr><td>数据库连接池</td><td>检查连接是否可用</td></tr><tr><td>消息队列 consumer</td><td>判断消费者是否在线</td></tr><tr><td>长任务执行器</td><td>防止任务永久 running</td></tr><tr><td>Agent 调度系统</td><td>判断 agent worker 是否失联</td></tr></tbody></table><hr><h2 id="_12-一句话总结" tabindex="-1">12. 一句话总结 <a class="header-anchor" href="#_12-一句话总结" aria-label="Permalink to &quot;12. 一句话总结&quot;">​</a></h2><p><strong>Heartbeat 是 worker 定期报活；TTL 是这个报活或任务占用的有效期；PID liveness 只能说明进程没死，heartbeat 才说明 worker 还能和系统通信；TTL 到期后，系统可以把任务从失联 worker 手里回收并重新调度。</strong></p><p>更工程化地说：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Heartbeat + TTL + claim_lock + retry_count</span></span>
<span class="line"><span>= 后台任务系统的健康检查与失败恢复机制</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/hermes/kanban/Worker 心跳与任务租约.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Worker________ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Worker________ as default
};
