import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"多 Gateway 与 Dispatcher 部署","description":"","frontmatter":{},"headers":[],"relativePath":"projects/hermes/kanban/多 Gateway 与 Dispatcher 部署.md","filePath":"projects/hermes/kanban/多 Gateway 与 Dispatcher 部署.md"}');
const _sfc_main = { name: "projects/hermes/kanban/多 Gateway 与 Dispatcher 部署.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="多-gateway-与-dispatcher-部署" tabindex="-1">多 Gateway 与 Dispatcher 部署 <a class="header-anchor" href="#多-gateway-与-dispatcher-部署" aria-label="Permalink to &quot;多 Gateway 与 Dispatcher 部署&quot;">​</a></h1><p>这篇笔记整理自 <code>multi-gateway.md</code>，用于理解多个 gateway 同时运行时，Kanban dispatcher 应该如何部署。</p><h2 id="背景" tabindex="-1">背景 <a class="header-anchor" href="#背景" aria-label="Permalink to &quot;背景&quot;">​</a></h2><p>Hermes 可以同时运行多个 gateway 进程。</p><p>例如不同 profile 各自有一个 gateway：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>default</span></span>
<span class="line"><span>writer</span></span>
<span class="line"><span>admin</span></span>
<span class="line"><span>coder</span></span>
<span class="line"><span>researcher</span></span></code></pre></div><p>每个 gateway 都可以连接自己的平台 API，并为对应 profile 的订阅者转发消息。</p><h2 id="核心原则-只能有一个-gateway-负责-dispatcher" tabindex="-1">核心原则：只能有一个 gateway 负责 dispatcher <a class="header-anchor" href="#核心原则-只能有一个-gateway-负责-dispatcher" aria-label="Permalink to &quot;核心原则：只能有一个 gateway 负责 dispatcher&quot;">​</a></h2><p>虽然可以有多个 gateway，但 Kanban dispatcher 应该只由一个 gateway 负责。</p><p>通常是 <code>default</code> profile 的 gateway：</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">kanban</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  dispatch_in_gateway</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span></span></code></pre></div><p>其他 gateway 应该关闭：</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">kanban</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  dispatch_in_gateway</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span></code></pre></div><p>也可以用环境变量：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>HERMES_KANBAN_DISPATCH_IN_GATEWAY=false</span></span></code></pre></div><h2 id="为什么只能一个-dispatcher" tabindex="-1">为什么只能一个 dispatcher <a class="header-anchor" href="#为什么只能一个-dispatcher" aria-label="Permalink to &quot;为什么只能一个 dispatcher&quot;">​</a></h2><p>如果多个 gateway 都开启 <code>dispatch_in_gateway: true</code>，它们都会：</p><ul><li>打开每个 board 的 SQLite 连接</li><li>运行 dispatcher</li><li>运行 notifier watcher</li><li>轮询 <code>kanban.db</code></li></ul><p>这样会带来几个问题：</p><ul><li>每个 <code>kanban.db</code> 的文件描述符变多</li><li>SQLite WAL / <code>-shm</code> reader 竞争增加</li><li>多个进程同时碰同一个任务调度路径</li><li>更容易出现不必要的资源争用</li></ul><p>所以文档建议：</p><blockquote><p>多 gateway 可以并存，但 Kanban DB / dispatcher / notifier watcher 只交给一个进程负责。</p></blockquote><h2 id="各-gateway-的分工" tabindex="-1">各 gateway 的分工 <a class="header-anchor" href="#各-gateway-的分工" aria-label="Permalink to &quot;各 gateway 的分工&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Gateway</th><th>dispatch_in_gateway</th><th>是否打开 Kanban DB</th><th>是否运行 dispatcher / notifier</th></tr></thead><tbody><tr><td>default</td><td>true</td><td>是</td><td>是</td></tr><tr><td>writer / admin / coder 等</td><td>false</td><td>否</td><td>否</td></tr></tbody></table><p>关闭 dispatcher 的 gateway 仍然可以正常处理自己的平台消息，例如 Telegram、Discord 等。</p><p>它们只是“不轮询 Kanban board”。</p><h2 id="我的理解" tabindex="-1">我的理解 <a class="header-anchor" href="#我的理解" aria-label="Permalink to &quot;我的理解&quot;">​</a></h2><p>多 gateway 部署的关键不是“不能多开 gateway”，而是要避免多个 gateway 同时承担 Kanban 调度职责。</p><p>更准确地说：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>消息入口可以多个</span></span>
<span class="line"><span>Kanban dispatcher 最好一个</span></span></code></pre></div><p>这符合 Kanban 的设计思路：SQLite 是共享状态层，但调度和通知最好由一个明确的 owner 负责，减少并发争用和排查复杂度。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/hermes/kanban/多 Gateway 与 Dispatcher 部署.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const __Gateway___Dispatcher___ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  __Gateway___Dispatcher___ as default
};
