import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"增量聚类改造方案","description":"","frontmatter":{},"headers":[],"relativePath":"topics/algorithms/clustering/增量聚类改造方案.md","filePath":"topics/algorithms/clustering/增量聚类改造方案.md"}');
const _sfc_main = { name: "topics/algorithms/clustering/增量聚类改造方案.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="增量聚类改造方案" tabindex="-1">增量聚类改造方案 <a class="header-anchor" href="#增量聚类改造方案" aria-label="Permalink to &quot;增量聚类改造方案&quot;">​</a></h1><p>这份方案用于把 CluStream 的 <code>online micro-cluster</code> 思想裁剪到 Mira 记忆系统中。</p><p>目标不是完整复现 CluStream，而是解决当前工程问题：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>当前：cell 变化 -&gt; 全量读取所有 memcell -&gt; 全量重聚类</span></span>
<span class="line"><span>目标：cell 变化 -&gt; 只更新受影响 cluster</span></span></code></pre></div><h2 id="_1-设计结论" tabindex="-1">1. 设计结论 <a class="header-anchor" href="#_1-设计结论" aria-label="Permalink to &quot;1. 设计结论&quot;">​</a></h2><p>第一版采用：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>BIRCH-style Online Micro-Cluster</span></span></code></pre></div><p>也就是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>新 MemoryCell 进入</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>找同 user_id + kind 下最近的 cluster</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>用 cosine 判断是否能吸收</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>能吸收则用 CF 统计量增量更新</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>否则新建 cluster</span></span></code></pre></div><p>这里参考 BIRCH 的核心不是完整 CF Tree，而是它的 <code>Clustering Feature</code> 统计量：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N  = 成员数量</span></span>
<span class="line"><span>LS = 向量线性和，linear sum</span></span>
<span class="line"><span>SS = 向量平方范数和，sum of squared norms</span></span></code></pre></div><p>删除或修改 cell 时，优先用 <code>N / LS / SS</code> 做增量扣减；只有数据异常时才局部重算受影响 cluster。</p><p>保留全量重建能力，用于维护和迁移：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>recluster_all()</span></span>
<span class="line"><span>  -&gt; 清空 cluster / cluster_member</span></span>
<span class="line"><span>  -&gt; 从 memcell 表全量重建 cluster</span></span></code></pre></div><h2 id="_2-和-clustream-的对应关系" tabindex="-1">2. 和 CluStream 的对应关系 <a class="header-anchor" href="#_2-和-clustream-的对应关系" aria-label="Permalink to &quot;2. 和 CluStream 的对应关系&quot;">​</a></h2><p>CluStream / BIRCH 里的概念可以映射成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>data point          -&gt; MemoryCell</span></span>
<span class="line"><span>micro-cluster       -&gt; cluster 表中的一条记录</span></span>
<span class="line"><span>micro-cluster member-&gt; cluster_member 表</span></span>
<span class="line"><span>macro-cluster       -&gt; OME 派生出的 profile / skill / idea cell</span></span>
<span class="line"><span>snapshot            -&gt; 后续可选的 cluster_snapshot</span></span>
<span class="line"><span>BIRCH CF            -&gt; cluster 表里的 N / LS / SS / centroid</span></span></code></pre></div><p>第一版只实现：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>online micro-cluster + BIRCH CF 统计量</span></span></code></pre></div><p>暂不实现：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>pyramidal time frame</span></span>
<span class="line"><span>offline macro-kmeans</span></span>
<span class="line"><span>evolution analysis</span></span></code></pre></div><p>原因是 Mira 已经有 Markdown source of truth，可以随时重建派生状态；第一版优先降低当前全量重聚类成本。</p><h2 id="_3-当前问题" tabindex="-1">3. 当前问题 <a class="header-anchor" href="#_3-当前问题" aria-label="Permalink to &quot;3. 当前问题&quot;">​</a></h2><p>当前 <code>_refresh_clusters()</code> 的行为是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>读取 memcell 表所有 cell</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>按 (user_id, kind) 分组</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>每组按 created_at 排序</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>逐条在线归并</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>覆盖写入 cluster / cluster_member</span></span></code></pre></div><p>问题：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 每次 cell 变化都全量重聚类。</span></span>
<span class="line"><span>2. agent_case 可能触发 LLM 聚类，和全量刷新组合后容易烧 token。</span></span>
<span class="line"><span>3. cluster_member.score 当前固定写 1.0，没有真实相似度。</span></span>
<span class="line"><span>4. memcell 和 episode 会重复聚类。</span></span>
<span class="line"><span>5. cluster 只是当前快照，没有 algorithm_version，后续迁移不够清晰。</span></span></code></pre></div><h2 id="_4-第一版改造范围" tabindex="-1">4. 第一版改造范围 <a class="header-anchor" href="#_4-第一版改造范围" aria-label="Permalink to &quot;4. 第一版改造范围&quot;">​</a></h2><p>第一版做这些：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 新增 IncrementalClusterer。</span></span>
<span class="line"><span>2. 让 replace_cells_for_entries() 返回 changed / deleted cell 信息。</span></span>
<span class="line"><span>3. cascade 中用增量聚类替代默认全量 _refresh_clusters()。</span></span>
<span class="line"><span>4. 保留 _refresh_clusters()，改名或定位为 rebuild_clusters()。</span></span>
<span class="line"><span>5. 默认不聚类 kind=memcell。</span></span>
<span class="line"><span>6. cluster_member.score 写入真实相似度。</span></span>
<span class="line"><span>7. cluster 表增加 algorithm_version 和 CF 统计量字段。</span></span></code></pre></div><p>第一版暂不做：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. pyramidal snapshot。</span></span>
<span class="line"><span>2. offline macro-kmeans。</span></span>
<span class="line"><span>3. adaptive threshold。</span></span>
<span class="line"><span>4. pending / outlier buffer。</span></span>
<span class="line"><span>5. 默认 LLM refine。</span></span></code></pre></div><h2 id="_5-聚类对象范围" tabindex="-1">5. 聚类对象范围 <a class="header-anchor" href="#_5-聚类对象范围" aria-label="Permalink to &quot;5. 聚类对象范围&quot;">​</a></h2><p>建议默认参与聚类的 kind：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">CLUSTERABLE_KINDS</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;episode&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;atomic_fact&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;foresight&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;agent_case&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;agent_skill&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;idea_capture&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>暂不默认聚类：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>memcell</span></span>
<span class="line"><span>user_profile</span></span></code></pre></div><p>原因：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>memcell:</span></span>
<span class="line"><span>  这是 Mira 为了保留 boundary cell 额外引入的检索 kind，不是原始 memory doc type。</span></span>
<span class="line"><span>  当前它有两条来源：</span></span>
<span class="line"><span>    1. boundary detector 产出的 BoundaryMemCell 会直接写入 kind=memcell。</span></span>
<span class="line"><span>    2. episode Markdown entry 带 memcell_id 时，cascade 会再派生一个 kind=memcell。</span></span>
<span class="line"><span>  因此它更适合作为 boundary 追踪 / 检索对象，而不是 OME 聚类对象。</span></span>
<span class="line"><span>  如果同时聚类 memcell 和 episode，容易形成内容相近的镜像 cluster。</span></span>
<span class="line"><span></span></span>
<span class="line"><span>user_profile:</span></span>
<span class="line"><span>  本身是高层派生结果，继续聚类可能造成自我强化。</span></span></code></pre></div><h2 id="_6-birch-cf-公式设计" tabindex="-1">6. BIRCH CF 公式设计 <a class="header-anchor" href="#_6-birch-cf-公式设计" aria-label="Permalink to &quot;6. BIRCH CF 公式设计&quot;">​</a></h2><p>BIRCH 里的 <code>CF</code> 可以直接用于我们的增量维护，但距离判断需要改成适合 embedding 的 cosine 版本。</p><h3 id="_6-1-cf-定义" tabindex="-1">6.1 CF 定义 <a class="header-anchor" href="#_6-1-cf-定义" aria-label="Permalink to &quot;6.1 CF 定义&quot;">​</a></h3><p>对一个 cluster，设成员向量为：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>x1, x2, ..., xn</span></span></code></pre></div><p>维护：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N  = n</span></span>
<span class="line"><span>LS = x1 + x2 + ... + xn</span></span>
<span class="line"><span>SS = ||x1||^2 + ||x2||^2 + ... + ||xn||^2</span></span></code></pre></div><p>cluster 的中心向量：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>centroid = LS / N</span></span></code></pre></div><p>如果 embedding 是单位向量，那么：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>||xi||^2 ≈ 1</span></span>
<span class="line"><span>SS ≈ N</span></span></code></pre></div><p>但仍然建议保存 <code>SS</code>，因为它后续可以用于计算半径、离散度和异常检测。</p><h3 id="_6-2-新增-cell" tabindex="-1">6.2 新增 cell <a class="header-anchor" href="#_6-2-新增-cell" aria-label="Permalink to &quot;6.2 新增 cell&quot;">​</a></h3><p>新 cell 的向量为 <code>x</code>。</p><p>如果它被吸收到已有 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39;  = N + 1</span></span>
<span class="line"><span>LS&#39; = LS + x</span></span>
<span class="line"><span>SS&#39; = SS + ||x||^2</span></span>
<span class="line"><span>centroid&#39; = LS&#39; / N&#39;</span></span></code></pre></div><p>如果它不能被吸收，则新建 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N  = 1</span></span>
<span class="line"><span>LS = x</span></span>
<span class="line"><span>SS = ||x||^2</span></span>
<span class="line"><span>centroid = x</span></span></code></pre></div><h3 id="_6-3-删除-cell" tabindex="-1">6.3 删除 cell <a class="header-anchor" href="#_6-3-删除-cell" aria-label="Permalink to &quot;6.3 删除 cell&quot;">​</a></h3><p>删除旧 cell，旧向量为 <code>x</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39;  = N - 1</span></span>
<span class="line"><span>LS&#39; = LS - x</span></span>
<span class="line"><span>SS&#39; = SS - ||x||^2</span></span>
<span class="line"><span>centroid&#39; = LS&#39; / N&#39;</span></span></code></pre></div><p>如果：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39; &lt;= 0</span></span></code></pre></div><p>则删除该 cluster。</p><h3 id="_6-4-修改-cell" tabindex="-1">6.4 修改 cell <a class="header-anchor" href="#_6-4-修改-cell" aria-label="Permalink to &quot;6.4 修改 cell&quot;">​</a></h3><p>修改 cell 等价于：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>删除旧 cell + 新增新 cell</span></span></code></pre></div><p>如果旧向量为 <code>old_x</code>，新向量为 <code>new_x</code>，且确定它仍然留在同一个 cluster，可以写成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39;  = N</span></span>
<span class="line"><span>LS&#39; = LS - old_x + new_x</span></span>
<span class="line"><span>SS&#39; = SS - ||old_x||^2 + ||new_x||^2</span></span>
<span class="line"><span>centroid&#39; = LS&#39; / N&#39;</span></span></code></pre></div><p>但工程上建议把修改处理为两步：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>remove old cell from old cluster</span></span>
<span class="line"><span>assign new cell to best cluster</span></span></code></pre></div><p>因为内容修改后，它不一定还应该属于原 cluster。</p><h3 id="_6-5-合并两个-cluster" tabindex="-1">6.5 合并两个 cluster <a class="header-anchor" href="#_6-5-合并两个-cluster" aria-label="Permalink to &quot;6.5 合并两个 cluster&quot;">​</a></h3><p>如果后续需要合并两个 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N  = N1 + N2</span></span>
<span class="line"><span>LS = LS1 + LS2</span></span>
<span class="line"><span>SS = SS1 + SS2</span></span>
<span class="line"><span>centroid = LS / N</span></span></code></pre></div><p>这就是 BIRCH CF 的可加性。</p><h3 id="_6-6-cosine-吸收判断" tabindex="-1">6.6 cosine 吸收判断 <a class="header-anchor" href="#_6-6-cosine-吸收判断" aria-label="Permalink to &quot;6.6 cosine 吸收判断&quot;">​</a></h3><p>BIRCH 原始论文更偏欧氏距离场景。Mira 的 MemoryCell 是 embedding，更适合用 cosine。</p><p>对新 cell 向量 <code>x</code> 和 cluster 中心 <code>centroid</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>centroid_unit = normalize(centroid)</span></span>
<span class="line"><span>score = cosine(x, centroid_unit)</span></span></code></pre></div><p>如果：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score &gt;= threshold(kind)</span></span></code></pre></div><p>则吸收进该 cluster。</p><p>否则新建 cluster。</p><p>第一版不使用 BIRCH 原始半径阈值作为主判断，避免和 embedding cosine 语义冲突。</p><h3 id="_6-7-cohesion-dispersion" tabindex="-1">6.7 cohesion / dispersion <a class="header-anchor" href="#_6-7-cohesion-dispersion" aria-label="Permalink to &quot;6.7 cohesion / dispersion&quot;">​</a></h3><p>有了 <code>N / LS / SS</code>，可以计算 cluster 的方向一致性。</p><p>推荐记录或调试时计算：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cohesion = ||LS|| / N</span></span>
<span class="line"><span>dispersion = 1 - cohesion</span></span></code></pre></div><p>直觉：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cohesion 越接近 1，成员方向越一致。</span></span>
<span class="line"><span>dispersion 越接近 0，cluster 越紧。</span></span></code></pre></div><p>第一版先不把它作为硬规则，只用于观测和验收。</p><p>后续可以增加规则：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>如果吸收新 cell 后 dispersion 超过上限，则拒绝吸收，改为新建 cluster。</span></span></code></pre></div><h3 id="_6-8-欧氏半径公式" tabindex="-1">6.8 欧氏半径公式 <a class="header-anchor" href="#_6-8-欧氏半径公式" aria-label="Permalink to &quot;6.8 欧氏半径公式&quot;">​</a></h3><p>如果后续需要兼容 BIRCH 原始半径概念，可以计算：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>radius^2 = SS / N - ||LS / N||^2</span></span></code></pre></div><p>但第一版不建议用它做主阈值。</p><p>原因：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. embedding 检索主路径使用 cosine。</span></span>
<span class="line"><span>2. 向量通常接近单位长度。</span></span>
<span class="line"><span>3. cosine 相似度对语义 embedding 更直观。</span></span></code></pre></div><h2 id="_7-数据库改造" tabindex="-1">7. 数据库改造 <a class="header-anchor" href="#_7-数据库改造" aria-label="Permalink to &quot;7. 数据库改造&quot;">​</a></h2><p>当前 <code>cluster</code> 表已有：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_id</span></span>
<span class="line"><span>owner_id</span></span>
<span class="line"><span>kind</span></span>
<span class="line"><span>label</span></span>
<span class="line"><span>centroid_json</span></span>
<span class="line"><span>member_count</span></span>
<span class="line"><span>last_ts</span></span>
<span class="line"><span>preview</span></span>
<span class="line"><span>updated_at</span></span></code></pre></div><p>第一版建议新增：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>algorithm_version TEXT NOT NULL DEFAULT &#39;micro_cluster_v1&#39;</span></span>
<span class="line"><span>created_at TEXT</span></span>
<span class="line"><span>ls_vector_json TEXT NOT NULL DEFAULT &#39;[]&#39;</span></span>
<span class="line"><span>ss_scalar REAL NOT NULL DEFAULT 0.0</span></span>
<span class="line"><span>cohesion REAL</span></span>
<span class="line"><span>dispersion REAL</span></span></code></pre></div><p>字段含义：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>ls_vector_json = BIRCH CF 里的 LS</span></span>
<span class="line"><span>ss_scalar      = BIRCH CF 里的 SS，保存 sum(||x||^2)</span></span>
<span class="line"><span>cohesion       = ||LS|| / N</span></span>
<span class="line"><span>dispersion     = 1 - cohesion</span></span></code></pre></div><p><code>cluster_member</code> 表当前已有：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_id</span></span>
<span class="line"><span>member_type</span></span>
<span class="line"><span>member_id</span></span>
<span class="line"><span>cell_id</span></span>
<span class="line"><span>score</span></span></code></pre></div><p>第一版复用 <code>score</code>，但语义改为：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = cell 分配进 cluster 时的 cosine similarity</span></span></code></pre></div><p>如果是新建 cluster 的第一个成员：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = 1.0</span></span></code></pre></div><p>后续可以再加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>added_at</span></span></code></pre></div><p>但第一版不是必须。</p><h2 id="_8-cellreplaceresult-改造" tabindex="-1">8. CellReplaceResult 改造 <a class="header-anchor" href="#_8-cellreplaceresult-改造" aria-label="Permalink to &quot;8. CellReplaceResult 改造&quot;">​</a></h2><p>当前 <code>replace_cells_for_entries()</code> 只返回是否 changed。</p><p>需要扩展为：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">@dataclass</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">frozen</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">True</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> CellReplaceResult</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    changed: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">bool</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    inserted_or_updated: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">int</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    unchanged: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">int</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    deleted: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">int</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    inserted_or_updated_cell_ids: list[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">str</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    deleted_cell_ids: list[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">str</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span></code></pre></div><p>或者更直接返回对象：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">changed_cells: list[MemoryCell]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">deleted_cell_ids: list[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">str</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span></code></pre></div><p>推荐返回：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>changed_cells</span></span>
<span class="line"><span>deleted_cell_ids</span></span></code></pre></div><p>因为 cascade 后续做增量聚类时需要完整 cell 内容和 vector。</p><h2 id="_9-增量聚类流程" tabindex="-1">9. 增量聚类流程 <a class="header-anchor" href="#_9-增量聚类流程" aria-label="Permalink to &quot;9. 增量聚类流程&quot;">​</a></h2><p>入口：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">clusterer.update(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    changed_cells</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">replace_result.changed_cells,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    deleted_cell_ids</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">replace_result.deleted_cell_ids,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span></code></pre></div><p>流程：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 删除旧 cell：用 CF 统计量从原 cluster 中扣减。</span></span>
<span class="line"><span>2. 新增新 cell：找最近 cluster，并用 CF 统计量吸收或新建。</span></span>
<span class="line"><span>3. 如果 CF 状态异常，再对受影响 cluster 做局部重算修复。</span></span></code></pre></div><h3 id="_9-1-删除旧-cell-cf-扣减" tabindex="-1">9.1 删除旧 cell：CF 扣减 <a class="header-anchor" href="#_9-1-删除旧-cell-cf-扣减" aria-label="Permalink to &quot;9.1 删除旧 cell：CF 扣减&quot;">​</a></h3><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>deleted_cell_ids</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>查 cluster_member，拿 old_cluster_id</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>读取旧 cell 的 vector_json</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>从 cluster 的 N / LS / SS 中扣减</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>删除 cluster_member</span></span></code></pre></div><p>对每个被删除的 cell：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39;  = N - 1</span></span>
<span class="line"><span>LS&#39; = LS - x</span></span>
<span class="line"><span>SS&#39; = SS - ||x||^2</span></span></code></pre></div><p>如果：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39; &lt;= 0</span></span></code></pre></div><p>则删除空 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE FROM cluster_member WHERE cluster_id = ?</span></span>
<span class="line"><span>DELETE FROM cluster WHERE cluster_id = ?</span></span></code></pre></div><p>否则更新 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>centroid&#39; = LS&#39; / N&#39;</span></span>
<span class="line"><span>cohesion&#39; = ||LS&#39;|| / N&#39;</span></span>
<span class="line"><span>dispersion&#39; = 1 - cohesion&#39;</span></span></code></pre></div><p><code>last_ts</code> 和 <code>preview</code> 有一个细节：如果删除的不是最新成员，可以保持不变；如果删除的是最新成员或 preview 成员，则需要从该 cluster 的剩余 members 里局部刷新：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>refresh_cluster_metadata(cluster_id):</span></span>
<span class="line"><span>  last_ts = max(remaining.created_at)</span></span>
<span class="line"><span>  preview = 最近 5 条 text[:200]</span></span></code></pre></div><p>也就是说，删除路径的主逻辑仍然是 CF 增量扣减；只有 <code>last_ts / preview</code> 这种展示型字段需要按 cluster 局部读取。</p><h3 id="_9-2-新增-cell-cf-吸收或新建" tabindex="-1">9.2 新增 cell：CF 吸收或新建 <a class="header-anchor" href="#_9-2-新增-cell-cf-吸收或新建" aria-label="Permalink to &quot;9.2 新增 cell：CF 吸收或新建&quot;">​</a></h3><p>对每个 changed cell：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>如果 kind 不在 CLUSTERABLE_KINDS:</span></span>
<span class="line"><span>  跳过</span></span>
<span class="line"><span></span></span>
<span class="line"><span>读取同 owner_id + kind + algorithm_version 的 clusters</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>按 time_window 过滤</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>计算 cosine(cell_vector, normalize(cluster.centroid))</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>选 top1</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>top1.score &gt;= threshold:</span></span>
<span class="line"><span>    absorb_cell(cluster, cell, score)</span></span>
<span class="line"><span>否则:</span></span>
<span class="line"><span>    create_cluster(cell)</span></span></code></pre></div><p>吸收时：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N&#39;  = N + 1</span></span>
<span class="line"><span>LS&#39; = LS + x</span></span>
<span class="line"><span>SS&#39; = SS + ||x||^2</span></span>
<span class="line"><span>centroid&#39; = LS&#39; / N&#39;</span></span>
<span class="line"><span>cohesion&#39; = ||LS&#39;|| / N&#39;</span></span>
<span class="line"><span>dispersion&#39; = 1 - cohesion&#39;</span></span></code></pre></div><p>然后写入成员关系：</p><div class="language-sql vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">INSERT INTO</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> cluster_member(cluster_id, member_type, member_id, cell_id, score)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">VALUES</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (?, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;memcell&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, ?, ?, ?)</span></span></code></pre></div><p>这里的 <code>score</code> 是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = cosine(cell_vector, normalize(old_centroid))</span></span></code></pre></div><p>新建 cluster 时：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_id = &quot;cluster_&quot; + cell.cell_id</span></span>
<span class="line"><span>N = 1</span></span>
<span class="line"><span>LS = x</span></span>
<span class="line"><span>SS = ||x||^2</span></span>
<span class="line"><span>centroid = x</span></span>
<span class="line"><span>cohesion = ||x|| / 1</span></span>
<span class="line"><span>dispersion = 1 - cohesion</span></span>
<span class="line"><span>preview = cell.text[:200]</span></span>
<span class="line"><span>score = 1.0</span></span></code></pre></div><h3 id="_9-3-修改-cell" tabindex="-1">9.3 修改 cell <a class="header-anchor" href="#_9-3-修改-cell" aria-label="Permalink to &quot;9.3 修改 cell&quot;">​</a></h3><p>Markdown entry 修改时，旧 cell 和新 cell 的内容、hash、embedding 都可能变化。</p><p>因此修改不要在原 cluster 里原地更新，而是拆成两步：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>remove old cell from old cluster</span></span>
<span class="line"><span>assign new cell to best cluster</span></span></code></pre></div><p>这样可以处理：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 修改后仍属于原 cluster。</span></span>
<span class="line"><span>2. 修改后应该进入另一个 cluster。</span></span>
<span class="line"><span>3. 修改后应该新建 cluster。</span></span></code></pre></div><h3 id="_9-4-局部重算-异常恢复路径" tabindex="-1">9.4 局部重算：异常恢复路径 <a class="header-anchor" href="#_9-4-局部重算-异常恢复路径" aria-label="Permalink to &quot;9.4 局部重算：异常恢复路径&quot;">​</a></h3><p>局部重算不是日常主路径，而是 repair fallback。</p><p>只在这些情况触发：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. cluster 的 N 和 cluster_member 数量对不上。</span></span>
<span class="line"><span>2. ls_vector_json 缺失或维度不一致。</span></span>
<span class="line"><span>3. ss_scalar 异常，例如小于 0。</span></span>
<span class="line"><span>4. cluster_member 指向的 memcell 不存在。</span></span>
<span class="line"><span>5. 维护命令显式要求 repair cluster。</span></span></code></pre></div><p>局部重算只处理 <code>affected_cluster_ids</code>，不是全量重聚类。</p><p><code>recompute_cluster(cluster_id)</code> 的读取逻辑是：</p><div class="language-sql vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  m</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cluster_id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  m</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cell_id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">kind</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">text</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">created_at</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">vector_json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> cluster_member m</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">JOIN</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> memcell c </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">ON</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cell_id</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> m</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cell_id</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> m</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cluster_id</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> ?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">ORDER BY</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">created_at</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cell_id</span></span></code></pre></div><p>如果没有剩余有效成员：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE FROM cluster_member WHERE cluster_id = ?</span></span>
<span class="line"><span>DELETE FROM cluster WHERE cluster_id = ?</span></span></code></pre></div><p>如果还有成员，则从成员向量重建 CF：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N  = len(valid_members)</span></span>
<span class="line"><span>LS = sum(member_vectors)</span></span>
<span class="line"><span>SS = sum(||vector||^2 for vector in member_vectors)</span></span>
<span class="line"><span>centroid = LS / N</span></span>
<span class="line"><span>cohesion = ||LS|| / N</span></span>
<span class="line"><span>dispersion = 1 - cohesion</span></span></code></pre></div><p>这里的 valid member 指：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_member 存在</span></span>
<span class="line"><span>memcell 也存在</span></span>
<span class="line"><span>vector_json 可解析</span></span>
<span class="line"><span>向量维度正确</span></span></code></pre></div><h3 id="_9-5-last-ts-怎么算" tabindex="-1">9.5 last_ts 怎么算 <a class="header-anchor" href="#_9-5-last-ts-怎么算" aria-label="Permalink to &quot;9.5 last_ts 怎么算&quot;">​</a></h3><p><code>last_ts</code> 取剩余成员里最大的 <code>created_at</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>last_ts = max(member.created_at)</span></span></code></pre></div><p>注意这里保存的是 ISO 时间字符串，而聚类比较时会转成 epoch ms。</p><h3 id="_9-6-preview-怎么生成" tabindex="-1">9.6 preview 怎么生成 <a class="header-anchor" href="#_9-6-preview-怎么生成" aria-label="Permalink to &quot;9.6 preview 怎么生成&quot;">​</a></h3><p>preview 不是完整文本，只是 cluster 的可读预览。</p><p>第一版规则：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>按 created_at 升序排序</span></span>
<span class="line"><span>取最后 5 个成员</span></span>
<span class="line"><span>每个成员取 text[:200]</span></span>
<span class="line"><span>用换行拼接</span></span>
<span class="line"><span>最终最多保留 500 字符</span></span></code></pre></div><p>伪代码：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">preview_items </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> [member.text[:</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">200</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">] </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">for</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> member </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">in</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> sorted_members[</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">5</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:]]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">preview </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">\\n</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.join(preview_items)[</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">500</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:]</span></span></code></pre></div><p>这样 cluster 的 preview 更偏向最近内容，符合长期记忆“近事更重要”的直觉。</p><h3 id="_9-7-cluster-member-score-要不要重算" tabindex="-1">9.7 cluster_member.score 要不要重算 <a class="header-anchor" href="#_9-7-cluster-member-score-要不要重算" aria-label="Permalink to &quot;9.7 cluster_member.score 要不要重算&quot;">​</a></h3><p>日常增量路径里，新增成员的 <code>score</code> 写入分配时的相似度：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = cosine(cell_vector, normalize(old_centroid))</span></span></code></pre></div><p>如果触发 <code>recompute_cluster()</code>，可以同步更新所有剩余成员的 score：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = cosine(member_vector, new_centroid)</span></span></code></pre></div><p>这样 <code>cluster_member.score</code> 始终表示：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>当前成员和当前 cluster centroid 的相似度</span></span></code></pre></div><p>而不是“当初被分配进来时的相似度”。</p><p>对应更新逻辑：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE FROM cluster_member WHERE cluster_id = ?</span></span>
<span class="line"><span>重新 INSERT 所有剩余成员，score 写 cosine(member_vector, new_centroid)</span></span></code></pre></div><p>这样实现简单，也和当前 <code>upsert_cluster()</code> 的覆盖式写入风格一致。</p><h3 id="_9-8-是否自动拆分-cluster" tabindex="-1">9.8 是否自动拆分 cluster <a class="header-anchor" href="#_9-8-是否自动拆分-cluster" aria-label="Permalink to &quot;9.8 是否自动拆分 cluster&quot;">​</a></h3><p>第一版不做自动拆分。</p><p>也就是说，如果一个 cluster 删除若干成员后内部变得不紧密，第一版不会自动拆成多个 cluster。</p><p>原因：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 自动拆分需要更复杂的簇内聚类算法。</span></span>
<span class="line"><span>2. 删除/修改通常只影响少量成员，先保证工程路径稳定。</span></span>
<span class="line"><span>3. 如果怀疑 cluster 污染，可以通过 recluster_all() 全量重建。</span></span></code></pre></div><p>后续可以增加维护命令：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>recluster_dirty_clusters()</span></span></code></pre></div><p>专门处理低内聚 cluster。</p><h2 id="_10-阈值建议" tabindex="-1">10. 阈值建议 <a class="header-anchor" href="#_10-阈值建议" aria-label="Permalink to &quot;10. 阈值建议&quot;">​</a></h2><p>第一版先用固定配置，不做自适应：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode:      threshold=0.65, time_window_days=7</span></span>
<span class="line"><span>atomic_fact:  threshold=0.70, time_window_days=30</span></span>
<span class="line"><span>foresight:    threshold=0.70, time_window_days=30</span></span>
<span class="line"><span>agent_case:   threshold=0.70, time_window_days=90</span></span>
<span class="line"><span>agent_skill:  threshold=0.75, time_window_days=365</span></span>
<span class="line"><span>idea_capture: threshold=0.68, time_window_days=90</span></span></code></pre></div><p>说明：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode 时间性强，窗口短一些。</span></span>
<span class="line"><span>atomic_fact / foresight 可以跨更长时间。</span></span>
<span class="line"><span>idea_capture 往往围绕长期项目，窗口更长。</span></span>
<span class="line"><span>agent_skill 更像长期经验，窗口最长。</span></span></code></pre></div><h2 id="_11-冷启动与迁移" tabindex="-1">11. 冷启动与迁移 <a class="header-anchor" href="#_11-冷启动与迁移" aria-label="Permalink to &quot;11. 冷启动与迁移&quot;">​</a></h2><p>增量聚类需要处理几个边界情况。</p><h3 id="_11-1-新系统没有-cluster" tabindex="-1">11.1 新系统没有 cluster <a class="header-anchor" href="#_11-1-新系统没有-cluster" aria-label="Permalink to &quot;11.1 新系统没有 cluster&quot;">​</a></h3><p>如果：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>memcell 已经有 vector</span></span>
<span class="line"><span>cluster 表为空</span></span></code></pre></div><p>则第一个可聚类 cell 直接新建 cluster：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>N = 1</span></span>
<span class="line"><span>LS = cell.vector</span></span>
<span class="line"><span>SS = ||cell.vector||^2</span></span>
<span class="line"><span>centroid = cell.vector</span></span></code></pre></div><p>这属于正常冷启动，不需要特殊兜底。</p><h3 id="_11-2-旧库没有-ls-ss" tabindex="-1">11.2 旧库没有 LS / SS <a class="header-anchor" href="#_11-2-旧库没有-ls-ss" aria-label="Permalink to &quot;11.2 旧库没有 LS / SS&quot;">​</a></h3><p>如果旧库已经有：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster</span></span>
<span class="line"><span>cluster_member</span></span>
<span class="line"><span>centroid_json</span></span></code></pre></div><p>但没有：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>ls_vector_json</span></span>
<span class="line"><span>ss_scalar</span></span>
<span class="line"><span>algorithm_version</span></span></code></pre></div><p>不能直接做增量更新。</p><p>启动或升级时应该执行一次：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>repair_clusters()</span></span></code></pre></div><p>流程：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>读取 cluster_member</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>JOIN memcell.vector_json</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>重新计算 N / LS / SS / centroid</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>回填 cluster 表</span></span></code></pre></div><p>如果某个 cluster 无法修复：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>成员 cell 不存在</span></span>
<span class="line"><span>vector_json 不存在</span></span>
<span class="line"><span>向量维度不一致</span></span></code></pre></div><p>则删除该 cluster，或让 <code>recluster_all()</code> 从 memcell 全量重建。</p><p>因为 cluster 是派生状态，删除后可重建。</p><h3 id="_11-3-cell-没有-vector" tabindex="-1">11.3 cell 没有 vector <a class="header-anchor" href="#_11-3-cell-没有-vector" aria-label="Permalink to &quot;11.3 cell 没有 vector&quot;">​</a></h3><p>如果某个 cell 没有 <code>vector_json</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>不能参与聚类</span></span></code></pre></div><p>cascade 顺序必须保证：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>upsert_cell()</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>embedder.embed()</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>写 memcell.vector_json</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>写 LanceDB</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>cluster assign</span></span></code></pre></div><p>如果 embedding 失败：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>本次 cascade job 应失败或重试</span></span>
<span class="line"><span>不应该创建无向量 cluster</span></span></code></pre></div><h3 id="_11-4-embedding-model-algorithm-version-不一致" tabindex="-1">11.4 embedding model / algorithm version 不一致 <a class="header-anchor" href="#_11-4-embedding-model-algorithm-version-不一致" aria-label="Permalink to &quot;11.4 embedding model / algorithm version 不一致&quot;">​</a></h3><p>cluster 表需要记录：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>embedding_model</span></span>
<span class="line"><span>algorithm_version</span></span></code></pre></div><p>如果当前配置和 cluster 记录不一致：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>不做增量更新</span></span>
<span class="line"><span>触发 repair 或 recluster_all</span></span></code></pre></div><p>典型场景：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>embedding 模型从 A 换到 B</span></span>
<span class="line"><span>向量维度变化</span></span>
<span class="line"><span>threshold 调整</span></span>
<span class="line"><span>算法从 micro_cluster_v1 升级到 micro_cluster_v2</span></span></code></pre></div><h2 id="_12-数据规模与文件增长策略" tabindex="-1">12. 数据规模与文件增长策略 <a class="header-anchor" href="#_12-数据规模与文件增长策略" aria-label="Permalink to &quot;12. 数据规模与文件增长策略&quot;">​</a></h2><p>长期运行时，数据增长压力主要来自历史材料和向量索引，不是 cluster 本身。</p><h3 id="_12-1-markdown-文件增长" tabindex="-1">12.1 Markdown 文件增长 <a class="header-anchor" href="#_12-1-markdown-文件增长" aria-label="Permalink to &quot;12.1 Markdown 文件增长&quot;">​</a></h3><p>当前 Markdown 路径规则：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode:</span></span>
<span class="line"><span>  users/&lt;user_id&gt;/&lt;session_id&gt;/ep-YYYY-MM-DD.md</span></span>
<span class="line"><span></span></span>
<span class="line"><span>atomic_fact:</span></span>
<span class="line"><span>  users/&lt;user_id&gt;/.atomic_facts/atomic_fact-YYYY-MM-DD.md</span></span>
<span class="line"><span></span></span>
<span class="line"><span>foresight:</span></span>
<span class="line"><span>  users/&lt;user_id&gt;/.foresights/foresight-YYYY-MM-DD.md</span></span>
<span class="line"><span></span></span>
<span class="line"><span>agent_case:</span></span>
<span class="line"><span>  agents/&lt;user_id&gt;/.cases/agent_case-YYYY-MM-DD.md</span></span>
<span class="line"><span></span></span>
<span class="line"><span>user_profile:</span></span>
<span class="line"><span>  users/&lt;user_id&gt;/user.md</span></span>
<span class="line"><span></span></span>
<span class="line"><span>agent_skill:</span></span>
<span class="line"><span>  agents/&lt;agent_id&gt;/skills/skill_&lt;name&gt;/SKILL.md</span></span></code></pre></div><p>增长最快的是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode</span></span>
<span class="line"><span>atomic_fact</span></span>
<span class="line"><span>session jsonl</span></span>
<span class="line"><span>LanceDB vector index</span></span>
<span class="line"><span>SQLite memcell.vector_json</span></span></code></pre></div><p>长期也不会很多的是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>user_profile</span></span>
<span class="line"><span>agent_skill</span></span>
<span class="line"><span>cluster</span></span>
<span class="line"><span>conversation_status</span></span>
<span class="line"><span>unprocessed_buffer</span></span>
<span class="line"><span>md_change_state</span></span></code></pre></div><h3 id="_12-2-哪些内容写-markdown" tabindex="-1">12.2 哪些内容写 Markdown <a class="header-anchor" href="#_12-2-哪些内容写-markdown" aria-label="Permalink to &quot;12.2 哪些内容写 Markdown&quot;">​</a></h3><p>Markdown 只存：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>人能读</span></span>
<span class="line"><span>人能改</span></span>
<span class="line"><span>能作为 source of truth</span></span>
<span class="line"><span>算法变化后能重建派生状态</span></span></code></pre></div><p>适合写 Markdown：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode</span></span>
<span class="line"><span>atomic_fact</span></span>
<span class="line"><span>foresight</span></span>
<span class="line"><span>agent_case</span></span>
<span class="line"><span>user_profile</span></span>
<span class="line"><span>agent_skill</span></span>
<span class="line"><span>idea_capture</span></span></code></pre></div><p>不适合写 Markdown：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster</span></span>
<span class="line"><span>cluster_member</span></span>
<span class="line"><span>N / LS / SS</span></span>
<span class="line"><span>ome_jobs</span></span>
<span class="line"><span>md_entry_state</span></span>
<span class="line"><span>sync queue</span></span>
<span class="line"><span>LanceDB index metadata</span></span></code></pre></div><p>这些是算法状态或派生索引，应该留在 SQLite / LanceDB。</p><h3 id="_12-3-cluster-不写-markdown" tabindex="-1">12.3 cluster 不写 Markdown <a class="header-anchor" href="#_12-3-cluster-不写-markdown" aria-label="Permalink to &quot;12.3 cluster 不写 Markdown&quot;">​</a></h3><p>cluster 是派生状态：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>memcell / episode / fact</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>cluster</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>OME 使用 cluster 做高层派生</span></span></code></pre></div><p>它不是事实源。</p><p>因此：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster 不写 Markdown</span></span>
<span class="line"><span>cluster_snapshot 第一版不做</span></span>
<span class="line"><span>cluster 可从 memcell 全量重建</span></span></code></pre></div><p>这样可以避免文件数量因为聚类算法增长而爆炸。</p><h3 id="_12-4-长期维护策略" tabindex="-1">12.4 长期维护策略 <a class="header-anchor" href="#_12-4-长期维护策略" aria-label="Permalink to &quot;12.4 长期维护策略&quot;">​</a></h3><p>建议后续增加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>repair_clusters()</span></span>
<span class="line"><span>  不改变成员归属，只重算 N / LS / SS / centroid。</span></span>
<span class="line"><span></span></span>
<span class="line"><span>recluster_all()</span></span>
<span class="line"><span>  清空 cluster，从 memcell 重新决定成员归属。</span></span>
<span class="line"><span></span></span>
<span class="line"><span>archive_sessions()</span></span>
<span class="line"><span>  归档较老 session jsonl。</span></span>
<span class="line"><span></span></span>
<span class="line"><span>dedupe_atomic_facts()</span></span>
<span class="line"><span>  对 atomic_fact 做去重或合并。</span></span></code></pre></div><p>其中：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>repair_clusters = 校准统计量</span></span>
<span class="line"><span>recluster_all   = 重新聚类</span></span></code></pre></div><p>这两个不能混淆。</p><h2 id="_13-llm-聚类策略" tabindex="-1">13. LLM 聚类策略 <a class="header-anchor" href="#_13-llm-聚类策略" aria-label="Permalink to &quot;13. LLM 聚类策略&quot;">​</a></h2><p>第一版默认关闭 LLM 聚类。</p><p>原因：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. token 成本不可控。</span></span>
<span class="line"><span>2. 当前 agent_case 数据还少。</span></span>
<span class="line"><span>3. 增量聚类第一版先追求稳定和可验收。</span></span></code></pre></div><p>后续可选策略：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>agent_case:</span></span>
<span class="line"><span>  similarity &gt;= 0.78 -&gt; 直接并入</span></span>
<span class="line"><span>  similarity &lt;= 0.50 -&gt; 直接新建</span></span>
<span class="line"><span>  0.50 &lt; similarity &lt; 0.78 -&gt; 可选 LLM refine</span></span></code></pre></div><p>LLM refine 应该只在维护任务或显式配置打开时运行。</p><h2 id="_14-和-ome-的关系" tabindex="-1">14. 和 OME 的关系 <a class="header-anchor" href="#_14-和-ome-的关系" aria-label="Permalink to &quot;14. 和 OME 的关系&quot;">​</a></h2><p>OME 当前会读取 cluster，找相关成员做 profile / skill 抽取。</p><p>第一版保持 OME 读取方式不变：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster -&gt; cluster_member -&gt; memcell</span></span></code></pre></div><p>增量聚类只改变 cluster 的维护方式，不改变 OME 的抽取接口。</p><p>后续可以升级成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>先找 top clusters</span></span>
<span class="line"><span>再取 top cluster members</span></span>
<span class="line"><span>再交给 extractor</span></span></code></pre></div><p>但第一版不做。</p><h2 id="_15-全量重建" tabindex="-1">15. 全量重建 <a class="header-anchor" href="#_15-全量重建" aria-label="Permalink to &quot;15. 全量重建&quot;">​</a></h2><p>保留全量重建能力：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">rebuild_clusters()</span></span></code></pre></div><p>行为：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE FROM cluster;</span></span>
<span class="line"><span>DELETE FROM cluster_member;</span></span>
<span class="line"><span>读取所有 clusterable memcell;</span></span>
<span class="line"><span>按 created_at 排序;</span></span>
<span class="line"><span>逐个 assign_cell();</span></span></code></pre></div><p>触发场景：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>embedding 模型变化</span></span>
<span class="line"><span>threshold 变化</span></span>
<span class="line"><span>algorithm_version 变化</span></span>
<span class="line"><span>手动大规模改 Markdown</span></span>
<span class="line"><span>怀疑 cluster 被污染</span></span>
<span class="line"><span>调试 / 验收</span></span></code></pre></div><h2 id="_16-文件改造点" tabindex="-1">16. 文件改造点 <a class="header-anchor" href="#_16-文件改造点" aria-label="Permalink to &quot;16. 文件改造点&quot;">​</a></h2><p>建议新增：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>src/mira/plugins/memory/clustering.py</span></span></code></pre></div><p>职责：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>IncrementalClusterer</span></span>
<span class="line"><span>ClusterPolicy</span></span>
<span class="line"><span>CLUSTERABLE_KINDS</span></span>
<span class="line"><span>rebuild_clusters()</span></span>
<span class="line"><span>update_clusters()</span></span>
<span class="line"><span>assign_cell()</span></span>
<span class="line"><span>recompute_cluster()</span></span></code></pre></div><p>需要修改：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>src/mira/plugins/memory/db.py</span></span>
<span class="line"><span>  - 扩展 CellReplaceResult</span></span>
<span class="line"><span>  - 增加 cluster 查询 / CF 增量更新 / repair 重算辅助方法</span></span>
<span class="line"><span>  - cluster 表补 algorithm_version / created_at</span></span>
<span class="line"><span></span></span>
<span class="line"><span>src/mira/plugins/memory/cascade.py</span></span>
<span class="line"><span>  - 用 IncrementalClusterer 替换默认 _refresh_clusters()</span></span>
<span class="line"><span>  - 保留全量 rebuild_clusters()</span></span>
<span class="line"><span></span></span>
<span class="line"><span>src/mira/plugins/memory/service.py</span></span>
<span class="line"><span>  - rebuild() 时调用全量 recluster</span></span>
<span class="line"><span>  - inspect_state() 可显示 cluster algorithm version</span></span></code></pre></div><h2 id="_17-验收标准" tabindex="-1">17. 验收标准 <a class="header-anchor" href="#_17-验收标准" aria-label="Permalink to &quot;17. 验收标准&quot;">​</a></h2><p>第一版完成后，需要能验证：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 修改一个 Markdown entry，只重新处理对应 entry 的 cells。</span></span>
<span class="line"><span>2. 修改一个 cell 后，只影响相关 cluster，不全量重聚类。</span></span>
<span class="line"><span>3. 删除 entry 后，对应 cluster_member 被删除。</span></span>
<span class="line"><span>4. 空 cluster 会被删除。</span></span>
<span class="line"><span>5. cluster_member.score 不再全是 1.0。</span></span>
<span class="line"><span>6. memcell 默认不再参与聚类。</span></span>
<span class="line"><span>7. /memory rebuild 或内部 rebuild 仍能全量重建 cluster。</span></span>
<span class="line"><span>8. 检索主路径不受影响。</span></span>
<span class="line"><span>9. OME 仍能从 cluster 中读取候选。</span></span></code></pre></div><h2 id="_18-后续版本" tabindex="-1">18. 后续版本 <a class="header-anchor" href="#_18-后续版本" aria-label="Permalink to &quot;18. 后续版本&quot;">​</a></h2><p>第二版可以加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>pending / outlier cluster</span></span></code></pre></div><p>用于处理相似度不够明确的 cell。</p><p>第三版可以加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_snapshot</span></span>
<span class="line"><span>pyramidal time frame</span></span>
<span class="line"><span>evolution analysis</span></span></code></pre></div><p>用于分析：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>用户兴趣变化</span></span>
<span class="line"><span>项目方向变化</span></span>
<span class="line"><span>创意主题变化</span></span>
<span class="line"><span>长期偏好漂移</span></span></code></pre></div><p>但这些不应进入第一版。</p><h2 id="_19-一句话总结" tabindex="-1">19. 一句话总结 <a class="header-anchor" href="#_19-一句话总结" aria-label="Permalink to &quot;19. 一句话总结&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Mira 第一版不完整复现 CluStream，而是吸收它的 online micro-cluster 思想：日常只做增量更新，必要时从 Markdown / memcell 全量重建。</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("topics/algorithms/clustering/增量聚类改造方案.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const ________ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  ________ as default
};
