import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"","description":"","frontmatter":{},"headers":[],"relativePath":"topics/algorithms/clustering/其他项目使用的算法.md","filePath":"topics/algorithms/clustering/其他项目使用的算法.md"}');
const _sfc_main = { name: "topics/algorithms/clustering/其他项目使用的算法.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p>看完了。除了 MemCell boundary，当前真正用到的算法大概有这几条：</p><p><strong>1. Ingest 标准化算法</strong></p><p>在 <code>src/mira/plugins/memory/ingest.py</code>。</p><p>作用是把当前 turn 变成 <code>CanonicalMessage</code>，并生成确定性 <code>message_id</code>： <code>sha256 前 8 位</code> 是一个很短的内容指纹。</p><p><code>sha256</code> 是一种哈希算法：给它一段文本，它会算出一串固定长度的十六进制字符串。比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>session_id + timestamp + role + text</span></span>
<span class="line"><span>  -&gt; sha256</span></span>
<span class="line"><span>  -&gt; a3f91c2e7b8d...</span></span></code></pre></div><p>这里“前 8 位”就是只取开头 8 个字符：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>a3f91c2e</span></span></code></pre></div><p>在我们这里它用来让 <code>message_id</code> 更稳定、更不容易撞：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>m_&lt;session_id&gt;_&lt;timestamp_ms&gt;_&lt;index&gt;_&lt;sha256前8位&gt;</span></span></code></pre></div><p>假设同一个 session、同一个时间戳、同一个 index 下，用户消息内容不同，那么最后这个 hash 后缀也会不同。</p><p>例子：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>你好</span></span>
<span class="line"><span>-&gt; m_sess_xxx_1781445475000_0_f8b29ca1</span></span>
<span class="line"><span></span></span>
<span class="line"><span>你还记得之前说了什么？</span></span>
<span class="line"><span>-&gt; m_sess_xxx_1781445475000_0_7aa3e9d2</span></span></code></pre></div><p>所以它不是加密，也不是为了安全，只是一个<strong>内容指纹/去重标识</strong>。<br> 取前 8 位是为了 ID 不要太长。这个长度有小概率碰撞，但在单个 session 的消息 ID 场景里通常够用；如果特别追求稳，可以取前 12 或 16 位。</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>sha256(session_id + timestamp_ms + index + role + text)[:8]</span></span></code></pre></div><p>然后 <code>merge_dedupe_sort()</code> 把：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>buffered tail + fresh messages</span></span></code></pre></div><p>按 <code>message_id</code> 去重，再按 timestamp 排序。</p><p><strong>2. Markdown entry-level diff 算法</strong></p><p>在 <code>src/mira/plugins/memory/cascade.py:98</code> 起。</p><p>这个是同步 Markdown 到 DB / LanceDB 的核心：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>读整个 md 文档</span></span>
<span class="line"><span>  -&gt; extract_entries(document)</span></span>
<span class="line"><span>  -&gt; 对每个 entry 算 entry_content_hash</span></span>
<span class="line"><span>  -&gt; 和 SQLite 里的 entry_state 对比</span></span>
<span class="line"><span>  -&gt; 只对 changed entry 重新 derive_cells</span></span>
<span class="line"><span>  -&gt; 未变化 entry 复用 old cells</span></span>
<span class="line"><span>  -&gt; deleted entry 删除对应 cell</span></span></code></pre></div><p>所以现在不是整篇都重新 embedding 了，已经是 entry 级 diff。<br> 但它仍然会解析整篇 Markdown，因为要知道哪些 entry 存在、哪些被删了。</p><p><strong>3. Cell 派生算法</strong></p><p>在 <code>src/mira/plugins/memory/cascade.py:246</code>。</p><p>每个 Markdown entry 会派生成一个或两个 <code>MemoryCell</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>普通 cell:</span></span>
<span class="line"><span>  kind = episode / atomic_fact / foresight / user_profile / agent_case / agent_skill / idea_capture</span></span>
<span class="line"><span></span></span>
<span class="line"><span>如果 episode entry 带 memcell_id:</span></span>
<span class="line"><span>  额外生成 kind=&quot;memcell&quot; 的 boundary cell</span></span></code></pre></div><p>也就是说，一个 episode entry 通常会变成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>memcell cell + episode cell</span></span></code></pre></div><p>前者保留 boundary 结果，后者作为 episode 记忆进入检索。</p><p><strong>4. Embedding 算法</strong></p><p>在 <code>src/mira/plugins/memory/embedding.py</code>。</p><p>正式默认是 <code>OpenAICompatibleEmbedder</code>，也就是你配置的千问兼容接口：</p><div class="language-toml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">toml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">[</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">memory</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">embedding</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">model = </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;text-embedding-v3&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">base_url = </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;https://dashscope.aliyuncs.com/compatible-mode/v1&quot;</span></span></code></pre></div><p><code>HashingTestEmbedder</code> 还在，但注释明确说是测试用，不是生产默认。</p><p>中文关键词 tokenize 也在这里：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>正则分词</span></span>
<span class="line"><span>中文 token 额外拆成单字和 bigram</span></span></code></pre></div><p>这主要服务 BM25 / FTS 检索。</p><p><strong>5. LanceDB 检索算法</strong></p><p>在 <code>src/mira/plugins/memory/vector.py</code>。</p><p>有两路：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>sparse_search:</span></span>
<span class="line"><span>  LanceDB FTS 搜 text_tokens</span></span>
<span class="line"><span>  如果 FTS 失败，退到扫描 rows + token overlap 排分</span></span>
<span class="line"><span></span></span>
<span class="line"><span>vector_search:</span></span>
<span class="line"><span>  LanceDB 向量搜索</span></span>
<span class="line"><span>  distance 转 score = max(1.0 - distance, 0.0)</span></span></code></pre></div><p>这里要注意：代码里 source 叫 <code>&quot;BM25&quot;</code>，但 fallback 的 <code>_rank_keyword_rows()</code> 是 token overlap，不是真正 BM25。LanceDB FTS 内部可能是 BM25/FTS 排序，但本地 fallback 不是。</p><p><strong>6. 混合检索融合算法</strong></p><p>在 <code>src/mira/plugins/memory/db.py:895</code> 和 <code>src/everalgo/rank/fusion.py</code>。</p><p>当前用的是 RRF：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>dense_candidates = vector_search(...)</span></span>
<span class="line"><span>sparse_candidates = sparse_search(...)</span></span>
<span class="line"><span>ranked_ids = rrf(dense_candidates, sparse_candidates, k=60)</span></span></code></pre></div><p>RRF 公式是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>score = Σ 1 / (60 + rank_i)</span></span></code></pre></div><p>最后展示分数乘了 100：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>round(candidate.score * 100.0, 3)</span></span></code></pre></div><p><strong>7. Cascade 聚类算法</strong></p><p>在 <code>src/mira/plugins/memory/cascade.py:181</code> 和 <code>src/everalgo/clustering/algorithm.py</code>。</p><p>每次 cells 变化后，<code>_refresh_clusters()</code> 会按：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>(user_id, kind)</span></span></code></pre></div><p>把所有 memcell 重新聚类。</p><p>普通 kind 用几何聚类：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>cluster_by_geometry</span></span>
<span class="line"><span>cosine similarity &gt;= 0.65</span></span>
<span class="line"><span>time_window_days = 7</span></span></code></pre></div><p>合并方式是 weighted centroid：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>new_centroid = (old_centroid * old_count + new_vector) / total_count</span></span></code></pre></div><p><code>agent_case</code> 特殊一点：如果有 LLM provider，就用 <code>cluster_by_llm()</code>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>先取 top-30 近邻</span></span>
<span class="line"><span>如果 top1 similarity &gt;= 0.85，直接并入</span></span>
<span class="line"><span>否则让 LLM 判断并入哪个 cluster，或者返回 new</span></span></code></pre></div><p><strong>8. OME 直接抽取算法</strong></p><p>在 <code>src/mira/plugins/memory/ome.py:23</code> 和 <code>:236</code> 起。</p><p>每个 episode entry 会入 5 个 OME job：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>extract_atomic_facts</span></span>
<span class="line"><span>extract_foresight</span></span>
<span class="line"><span>extract_agent_case</span></span>
<span class="line"><span>extract_user_profile</span></span>
<span class="line"><span>extract_agent_skill</span></span></code></pre></div><p>直接抽取包括：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>AtomicFactExtractor</span></span>
<span class="line"><span>ForesightExtractor</span></span>
<span class="line"><span>AgentCaseExtractor</span></span></code></pre></div><p>它们来自 <code>src/everalgo/user_memory</code> / <code>src/everalgo/agent_memory</code>，都是 LLM JSON 结构化抽取。</p><p>其中 <code>foresight</code> 有证据校验：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">evidence </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">in</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> source.text</span></span></code></pre></div><p>也就是证据必须是原文连续子串。</p><p><strong>9. OME 聚类抽取算法</strong></p><p>在 <code>src/mira/plugins/memory/ome.py:341</code> 和 <code>:546</code> 起。</p><p><code>user_profile</code> 从这些 kind 里找近邻：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>episode</span></span>
<span class="line"><span>atomic_fact</span></span>
<span class="line"><span>user_profile</span></span></code></pre></div><p><code>agent_skill</code> 从这些 kind 里找近邻：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>agent_case</span></span>
<span class="line"><span>agent_skill</span></span></code></pre></div><p>具体做法是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>source.text embedding</span></span>
<span class="line"><span>  -&gt; 遍历已有 cluster members</span></span>
<span class="line"><span>  -&gt; 读取每个 member 的 vector_json</span></span>
<span class="line"><span>  -&gt; cosine(source_vector, member_vector)</span></span>
<span class="line"><span>  -&gt; 去重</span></span>
<span class="line"><span>  -&gt; score 降序</span></span>
<span class="line"><span>  -&gt; 取 top 12</span></span></code></pre></div><p>然后要求 <code>min_cluster_size=2</code>，才调用：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>ProfileExtractor</span></span>
<span class="line"><span>AgentSkillExtractor</span></span></code></pre></div><p><strong>10. 当前没接入主路径的算法</strong></p><p><code>src/everalgo/rank/</code> 里还有很多算法，比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>lr</span></span>
<span class="line"><span>vector_anchored</span></span>
<span class="line"><span>maxsim</span></span>
<span class="line"><span>agentic_retrieve</span></span>
<span class="line"><span>LLM rerank</span></span>
<span class="line"><span>case/profile/skill ranker</span></span></code></pre></div><p>但 Mira 当前 <code>MemoryDatabase.search()</code> 主路径只用到了 <code>rrf()</code>，没有接入这些更复杂的 ranker。</p><p>一句话总结：现在主路径算法是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>deterministic ingest</span></span>
<span class="line"><span>-&gt; LLM boundary</span></span>
<span class="line"><span>-&gt; Markdown entry diff</span></span>
<span class="line"><span>-&gt; embedding</span></span>
<span class="line"><span>-&gt; LanceDB sparse/vector</span></span>
<span class="line"><span>-&gt; RRF fusion</span></span>
<span class="line"><span>-&gt; geometry/LLM clustering</span></span>
<span class="line"><span>-&gt; OME direct + cluster extraction</span></span></code></pre></div><p>真正还需要警惕的是两个点：<br><code>BM25</code> 这个名字现在有点泛化，fallback 不是严格 BM25；另外 <code>_refresh_clusters()</code> 是 cells 变化后全量重聚类，不是增量维护 cluster 状态。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("topics/algorithms/clustering/其他项目使用的算法.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _________ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _________ as default
};
