import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"大模型 Tokenizer 与 Embedding","description":"","frontmatter":{},"headers":[],"relativePath":"topics/llm/pretraining/Tokenizer 与 Embedding.md","filePath":"topics/llm/pretraining/Tokenizer 与 Embedding.md"}');
const _sfc_main = { name: "topics/llm/pretraining/Tokenizer 与 Embedding.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="大模型-tokenizer-与-embedding" tabindex="-1">大模型 Tokenizer 与 Embedding <a class="header-anchor" href="#大模型-tokenizer-与-embedding" aria-label="Permalink to &quot;大模型 Tokenizer 与 Embedding&quot;">​</a></h1><p>大模型不能直接处理自然语言文本。它通常要先经过 tokenizer，把文本切成 token，再映射成 token id，最后由 embedding 层把 token id 变成向量。</p><p>可以先记住这条链路：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>文本</span></span>
<span class="line"><span>-&gt; tokenizer 切分</span></span>
<span class="line"><span>-&gt; token id 序列</span></span>
<span class="line"><span>-&gt; token embedding</span></span>
<span class="line"><span>-&gt; 加上 position embedding</span></span>
<span class="line"><span>-&gt; Transformer 输入</span></span></code></pre></div><h2 id="tokenizer-做了什么" tabindex="-1">Tokenizer 做了什么 <a class="header-anchor" href="#tokenizer-做了什么" aria-label="Permalink to &quot;Tokenizer 做了什么&quot;">​</a></h2><p>Tokenizer 处理文本时，会参照已经训练好的词表和切分规则，把文本变成 token id 序列，并且可以在前后加特殊符号。</p><p>更准确地说：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>tokenizer = 切分规则 + 词表 + merge 规则 + 特殊 token 表</span></span></code></pre></div><p>它不是临时随便切，而是根据训练 tokenizer 时学到的词表和合并规则来做。</p><p>比如一个 tokenizer 的词表大小是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>vocab_size = 4096</span></span></code></pre></div><p>意思是它最多有 4096 个 token id，包括普通文本片段、BPE 合并出来的常见片段，以及 <code>&lt;bos&gt;</code>、<code>&lt;eos&gt;</code> 这类特殊 token。</p><p>编码时大致发生这些事：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 按规则把文本粗分块</span></span>
<span class="line"><span>2. 每块转成 byte 或字符片段</span></span>
<span class="line"><span>3. 根据 BPE / Unigram / WordPiece 等规则合并常见片段</span></span>
<span class="line"><span>4. 每个 token 查词表，得到 token id</span></span></code></pre></div><p>所以文本不是直接变成向量，而是先变成编号。后面模型的 embedding 层再根据这些编号查表，把编号变成向量。</p><h2 id="词表大小的取舍" tabindex="-1">词表大小的取舍 <a class="header-anchor" href="#词表大小的取舍" aria-label="Permalink to &quot;词表大小的取舍&quot;">​</a></h2><p>词表设计的核心是在 <strong>token 数量</strong> 和 <strong>表达粒度</strong> 之间做平衡。</p><p>词表太小，比如 <code>vocab_size=4096</code>，优点是 embedding 参数少、输出层小、模型更轻。缺点是很多词会被切得很碎。</p><p>例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>internationalization</span></span>
<span class="line"><span>-&gt; inter / nat / ion / al / iz / ation</span></span></code></pre></div><p>中文也可能被切成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>大 / 型 / 语 / 言 / 模 / 型</span></span></code></pre></div><p>这样同一句话会占用更多 token，上下文窗口更快被填满，attention 计算也更贵。</p><p>词表太大，比如 <code>vocab_size=100000</code>，优点是常见词和短语可以作为完整 token，文本压缩率更高。缺点是 embedding 表和输出 softmax 层都会变大，低频 token 也更难学充分。</p><p>可以简单理解为：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>词表小：省参数，但费上下文。</span></span>
<span class="line"><span>词表大：省上下文，但费参数和训练数据。</span></span></code></pre></div><h2 id="压缩率很重要" tabindex="-1">压缩率很重要 <a class="header-anchor" href="#压缩率很重要" aria-label="Permalink to &quot;压缩率很重要&quot;">​</a></h2><p>判断 tokenizer 好不好，一个重要指标是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>同一段文本会被切成多少 token</span></span></code></pre></div><p>例如同一句中文：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我正在学习大语言模型微调</span></span></code></pre></div><p>tokenizer A 可能切成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我 / 正在 / 学习 / 大 / 语言 / 模型 / 微调</span></span></code></pre></div><p>tokenizer B 可能切成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我 / 正 / 在 / 学 / 习 / 大 / 语 / 言 / 模 / 型 / 微 / 调</span></span></code></pre></div><p>A 对中文更高效，因为同样的文字占用更少 token。</p><p>这对 LLM 很重要，因为上下文窗口是按 token 算的。同样是 4096 token，上下文压缩率越好，能塞进去的真实文字越多。</p><h2 id="多语言和代码场景" tabindex="-1">多语言和代码场景 <a class="header-anchor" href="#多语言和代码场景" aria-label="Permalink to &quot;多语言和代码场景&quot;">​</a></h2><p>如果模型主要服务中文，就不能只用英文语料训练 tokenizer。否则中文可能被切得很碎。</p><p>多语言 tokenizer 要考虑训练语料比例：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>英文、中文、代码、数学、符号、少数语言、emoji、网页噪声</span></span></code></pre></div><p>词表会偏向训练 tokenizer 时出现频率高的语言。如果英文占比太高，中文压缩率可能就差。</p><p>代码模型也要特别考虑 tokenizer。代码里有很多固定模式：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>def</span></span>
<span class="line"><span>class</span></span>
<span class="line"><span>import</span></span>
<span class="line"><span>return</span></span>
<span class="line"><span>snake_case</span></span>
<span class="line"><span>camelCase</span></span>
<span class="line"><span>括号</span></span>
<span class="line"><span>缩进</span></span>
<span class="line"><span>换行</span></span></code></pre></div><p>好的代码 tokenizer 往往会保留常见代码片段，比如 <code>&quot;def&quot;</code>、<code>&quot;return&quot;</code>、<code>&quot;self&quot;</code>、<code>&quot;__init__&quot;</code>、缩进和换行。否则代码会被切得很碎，影响训练效率和生成质量。</p><h2 id="特殊-token" tabindex="-1">特殊 token <a class="header-anchor" href="#特殊-token" aria-label="Permalink to &quot;特殊 token&quot;">​</a></h2><p>除了普通 token，词表里还会有特殊 token。常见包括：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&lt;bos&gt;：开始</span></span>
<span class="line"><span>&lt;eos&gt;：结束</span></span>
<span class="line"><span>&lt;pad&gt;：填充</span></span>
<span class="line"><span>&lt;unk&gt;：未知</span></span>
<span class="line"><span>&lt;mask&gt;：遮盖，BERT 类模型常用</span></span>
<span class="line"><span>&lt;user&gt; / &lt;assistant&gt; / &lt;system&gt;：对话角色</span></span>
<span class="line"><span>&lt;tool_call&gt; / &lt;tool_result&gt;：工具调用</span></span></code></pre></div><p>聊天模型尤其依赖特殊 token。一轮对话可能被组织成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&lt;system&gt;</span></span>
<span class="line"><span>你是一个助手</span></span>
<span class="line"><span>&lt;user&gt;</span></span>
<span class="line"><span>解释一下 LoRA</span></span>
<span class="line"><span>&lt;assistant&gt;</span></span>
<span class="line"><span>LoRA 是一种参数高效微调方法</span></span>
<span class="line"><span>&lt;eos&gt;</span></span></code></pre></div><p>如果特殊 token 和聊天模板设计混乱，SFT 数据格式就会乱，模型也更难学会什么时候回答、什么时候停止。</p><h2 id="常见-tokenizer-算法" tabindex="-1">常见 tokenizer 算法 <a class="header-anchor" href="#常见-tokenizer-算法" aria-label="Permalink to &quot;常见 tokenizer 算法&quot;">​</a></h2><p>常见算法大致有：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>BPE：GPT 系列常见，从小片段开始，把高频共现片段不断合并。</span></span>
<span class="line"><span>WordPiece：BERT 常见，也合并子词，但目标偏向最大化语言模型似然。</span></span>
<span class="line"><span>Unigram：SentencePiece / T5 常见，先准备候选子词，再删除不重要的。</span></span>
<span class="line"><span>Byte-level BPE：GPT-2、RoBERTa 常见，从 byte 开始，基本避免 OOV。</span></span></code></pre></div><p>现在大模型里，byte-level 或 byte fallback 很常见，因为它能避免遇到生僻字符就无法表示。</p><h2 id="训练-tokenizer-是什么" tabindex="-1">训练 tokenizer 是什么 <a class="header-anchor" href="#训练-tokenizer-是什么" aria-label="Permalink to &quot;训练 tokenizer 是什么&quot;">​</a></h2><p>训练 tokenizer 不等于训练神经网络。以 BPE 为例，它的“训练”更像是一个统计和贪心合并过程，而不是梯度下降。</p><p>模型训练通常是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>参数随机初始化</span></span>
<span class="line"><span>-&gt; 前向传播</span></span>
<span class="line"><span>-&gt; 计算 loss</span></span>
<span class="line"><span>-&gt; 反向传播</span></span>
<span class="line"><span>-&gt; 梯度下降更新参数</span></span></code></pre></div><p>BPE tokenizer 训练大致是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>读取大量文本</span></span>
<span class="line"><span>-&gt; 统计相邻字符 / byte 片段的出现频率</span></span>
<span class="line"><span>-&gt; 找到最常出现的一对片段</span></span>
<span class="line"><span>-&gt; 把它们合并成一个新 token</span></span>
<span class="line"><span>-&gt; 重复这个过程</span></span>
<span class="line"><span>-&gt; 直到达到设定的 vocab_size</span></span></code></pre></div><p>所以 BPE 训练没有 loss、gradient、backpropagation、optimizer、learning rate。它主要是在语料里统计哪些片段常见，哪些片段值得合并进词表。</p><p>一个简单例子：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>low</span></span>
<span class="line"><span>lower</span></span>
<span class="line"><span>lowest</span></span></code></pre></div><p>一开始可能拆成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>l o w</span></span>
<span class="line"><span>l o w e r</span></span>
<span class="line"><span>l o w e s t</span></span></code></pre></div><p>如果 <code>l + o</code> 最常出现，就合并成 <code>lo</code>；之后如果 <code>lo + w</code> 又很常见，就继续合并成 <code>low</code>。最后可能得到：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>lower  -&gt; low + er</span></span>
<span class="line"><span>lowest -&gt; low + est</span></span></code></pre></div><p>BPE 训练完成后，通常会得到词表和合并规则，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>vocab.json      # token 到 id 的映射</span></span>
<span class="line"><span>merges.txt      # BPE 合并规则</span></span>
<span class="line"><span>tokenizer.json  # 完整 tokenizer 配置</span></span></code></pre></div><p>所以这里要区分两件事：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>训练 tokenizer：</span></span>
<span class="line"><span>用统计方法学出 token、token id 和 merge 规则。</span></span>
<span class="line"><span></span></span>
<span class="line"><span>训练模型：</span></span>
<span class="line"><span>用梯度下降学习 embedding、attention、MLP 等模型参数。</span></span></code></pre></div><p>也就是说，tokenizer 先确定“有哪些 token、每个 token 的 id 是多少”；模型训练再确定“每个 token id 对应什么向量”。</p><h2 id="微调时通常不要改-tokenizer" tabindex="-1">微调时通常不要改 tokenizer <a class="header-anchor" href="#微调时通常不要改-tokenizer" aria-label="Permalink to &quot;微调时通常不要改 tokenizer&quot;">​</a></h2><p>如果只是微调 Qwen、LLaMA、GPT 类模型，通常不要自己改 tokenizer。</p><p>原因是 tokenizer 和模型 embedding 层是绑定的。乱改 tokenizer 会导致：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>token id 对不上</span></span>
<span class="line"><span>embedding 语义错乱</span></span>
<span class="line"><span>模型原有能力下降</span></span>
<span class="line"><span>需要重新训练 embedding</span></span></code></pre></div><p>实际项目里通常只做两件事：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 使用原模型自带 tokenizer</span></span>
<span class="line"><span>2. 必要时添加少量 special tokens，然后 resize_token_embeddings</span></span></code></pre></div><p>例如：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">tokenizer.add_special_tokens({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;additional_special_tokens&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;&lt;tool_call&gt;&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;&lt;tool_result&gt;&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">})</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">model.resize_token_embeddings(</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">len</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(tokenizer))</span></span></code></pre></div><p>但新增 token 的 embedding 通常是随机初始化的，还需要通过微调学出来。</p><p>只有在从零预训练模型、做特定语言或领域模型、原 tokenizer 压缩率很差，或者要设计自己的模型体系时，才更可能自己训练 tokenizer。</p><h2 id="token-embedding-本质是查表" tabindex="-1">Token embedding 本质是查表 <a class="header-anchor" href="#token-embedding-本质是查表" aria-label="Permalink to &quot;Token embedding 本质是查表&quot;">​</a></h2><p>Tokenizer 得到的是 token id，例如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>[1, 10, 25, 88, 2]</span></span></code></pre></div><p>Embedding 层会把这些 id 映射成向量。最小代码是：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> torch</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> torch.nn </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">as</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> nn</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">vocab_size </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 128</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">hidden_size </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 64</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">token_embedding </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> nn.Embedding(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    num_embeddings</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">vocab_size,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    embedding_dim</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">hidden_size,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">input_ids </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> torch.tensor([</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    [</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">10</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">25</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">88</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    [</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">33</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">44</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">55</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">])</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">x </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> token_embedding(input_ids)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">print</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(input_ids.shape)  </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># torch.Size([2, 5])</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">print</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(x.shape)          </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># torch.Size([2, 5, 64])</span></span></code></pre></div><p>含义是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>原来是 [2, 5]：</span></span>
<span class="line"><span>2 句话，每句话 5 个 token id</span></span>
<span class="line"><span></span></span>
<span class="line"><span>embedding 后是 [2, 5, 64]：</span></span>
<span class="line"><span>2 句话，每句话 5 个 token，每个 token 变成 64 维向量</span></span></code></pre></div><p>它内部本质上就是查表：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">x </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> token_embedding.weight[input_ids]</span></span></code></pre></div><p>如果 embedding 表形状是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>[128, 64]</span></span></code></pre></div><p>意思就是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>128 个 token</span></span>
<span class="line"><span>每个 token 一个 64 维向量</span></span></code></pre></div><h2 id="为什么还要-position-embedding" tabindex="-1">为什么还要 position embedding <a class="header-anchor" href="#为什么还要-position-embedding" aria-label="Permalink to &quot;为什么还要 position embedding&quot;">​</a></h2><p>Token embedding 只告诉模型“这个 token 是什么”，但不知道“这个 token 在第几个位置”。</p><p>比如：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>我 喜欢 你</span></span>
<span class="line"><span>你 喜欢 我</span></span></code></pre></div><p>这两个句子的 token 集合差不多，但顺序不同，意思不同。</p><p>所以 GPT 里通常会把 token embedding 和 position embedding 相加：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">x </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> token_emb </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">+</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> pos_emb</span></span></code></pre></div><p>最小结构类似这样：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> MiniGPTEmbedding</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">nn</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">Module</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> __init__</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self, vocab_size, max_seq_len, hidden_size):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        super</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">().</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">__init__</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.token_embedding </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> nn.Embedding(vocab_size, hidden_size)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.position_embedding </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> nn.Embedding(max_seq_len, hidden_size)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> forward</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self, input_ids):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">        batch_size, seq_len </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> input_ids.shape</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">        token_emb </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.token_embedding(input_ids)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">        position_ids </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> torch.arange(seq_len, </span><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">device</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">input_ids.device)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">        position_emb </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.position_embedding(position_ids)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> token_emb </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">+</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> position_emb</span></span></code></pre></div><p>在 Hugging Face GPT-2 里，对应关系通常是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>self.transformer.wte  # word token embedding</span></span>
<span class="line"><span>self.transformer.wpe  # word position embedding</span></span></code></pre></div><p>如果配置是：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">GPT2Config(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    vocab_size</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">128</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    n_positions</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">32</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">    n_embd</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">64</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span></code></pre></div><p>对应的 embedding 层就是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>token embedding:    [128, 64]</span></span>
<span class="line"><span>position embedding: [32, 64]</span></span></code></pre></div><h2 id="总结" tabindex="-1">总结 <a class="header-anchor" href="#总结" aria-label="Permalink to &quot;总结&quot;">​</a></h2><p>Tokenizer 的作用，是把文本按照词表和切分规则变成 token id。Embedding 的作用，是把 token id 查表变成向量。</p><p>一句话：</p><blockquote><p>文本先被 tokenizer 编码成 token id；token id 再通过 <code>nn.Embedding(vocab_size, hidden_size)</code> 变成向量，并加上位置信息，作为 Transformer 的输入。</p></blockquote><p>训练 tokenizer 主要是在语料上统计高频片段并学习词表和合并规则；真正通过梯度下降训练的是模型参数，比如 embedding、attention 和 MLP。</p><p>词表设计不是为了“看起来像单词”，而是为了让模型用尽量少的 token 表示尽量多的真实文本，同时让高频模式容易学习、低频内容也能组合出来。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("topics/llm/pretraining/Tokenizer 与 Embedding.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Tokenizer___Embedding = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Tokenizer___Embedding as default
};
