import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"大模型预训练数据的几种常见格式","description":"","frontmatter":{},"headers":[],"relativePath":"topics/llm/pretraining/预训练数据格式.md","filePath":"topics/llm/pretraining/预训练数据格式.md"}');
const _sfc_main = { name: "topics/llm/pretraining/预训练数据格式.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="大模型预训练数据的几种常见格式" tabindex="-1">大模型预训练数据的几种常见格式 <a class="header-anchor" href="#大模型预训练数据的几种常见格式" aria-label="Permalink to &quot;大模型预训练数据的几种常见格式&quot;">​</a></h1><p>大模型预训练数据本质上是大量文本和元信息的集合。不同数据格式的差别，主要体现在：</p><ul><li>是否方便人工查看</li><li>是否支持复杂结构</li><li>是否适合流式读取</li><li>是否适合大规模压缩和训练读取</li></ul><p>常见格式可以先这样理解：</p><table tabindex="0"><thead><tr><th>格式</th><th>特点</th><th>适合场景</th></tr></thead><tbody><tr><td>CSV</td><td>简单、可读，像表格</td><td>小规模表格数据、人工查看</td></tr><tr><td>JSON</td><td>结构灵活，支持嵌套</td><td>API、配置、结构化样本</td></tr><tr><td>JSONL</td><td>一行一个 JSON，方便逐行读取</td><td>NLP 数据集、指令数据、日志式数据</td></tr><tr><td>Parquet</td><td>二进制、列式、压缩好</td><td>大规模数据集、预训练数据</td></tr></tbody></table><p>如果只是几千条样本，CSV、JSON、JSONL 都够用。但预训练数据通常非常大，可能是几百 GB、几 TB，甚至更多。这时重点就不只是“能不能存”，而是“能不能高效读取、压缩和分块处理”。</p><h2 id="jsonl-训练数据里很常见的文本格式" tabindex="-1">JSONL：训练数据里很常见的文本格式 <a class="header-anchor" href="#jsonl-训练数据里很常见的文本格式" aria-label="Permalink to &quot;JSONL：训练数据里很常见的文本格式&quot;">​</a></h2><p>JSONL 是一行一个 JSON 对象，例如：</p><div class="language-jsonl vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">jsonl</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;text&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;今天学习大模型&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;source&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;web&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;text&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Transformer 是一种架构&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;source&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;book&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;text&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;LoRA 用于参数高效微调&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">&quot;source&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;paper&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>它的好处是简单、直观、容易追加，也方便一行一行读取。很多微调数据、指令数据、评测数据都会用 JSONL。</p><p>但它的问题也明显：数据量很大时，文本格式体积偏大；如果只想读其中某个字段，也通常还是要解析整行 JSON。</p><h2 id="parquet-更适合大规模训练数据" tabindex="-1">Parquet：更适合大规模训练数据 <a class="header-anchor" href="#parquet-更适合大规模训练数据" aria-label="Permalink to &quot;Parquet：更适合大规模训练数据&quot;">​</a></h2><p>Parquet 是一种数据文件格式，全名一般叫 <strong>Apache Parquet</strong>。它适合存储大规模表格数据。</p><p>逻辑上，它存的内容也可以像普通表格一样：</p><table tabindex="0"><thead><tr><th>id</th><th>text</th><th>source</th></tr></thead><tbody><tr><td>1</td><td>今天学习大模型</td><td>web</td></tr><tr><td>2</td><td>Transformer 是一种架构</td><td>book</td></tr><tr><td>3</td><td>LoRA 用于参数高效微调</td><td>paper</td></tr></tbody></table><p>区别在于，Parquet 不是普通文本文件，而是二进制格式。它更适合压缩、分块和高效读取。</p><h2 id="parquet-的核心特点-列式存储" tabindex="-1">Parquet 的核心特点：列式存储 <a class="header-anchor" href="#parquet-的核心特点-列式存储" aria-label="Permalink to &quot;Parquet 的核心特点：列式存储&quot;">​</a></h2><p>CSV、JSONL 更接近“按行存储”。而 Parquet 是按列存储：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>id 列：1, 2, 3, ...</span></span>
<span class="line"><span>text 列：今天学习大模型, Transformer 是一种架构, ...</span></span>
<span class="line"><span>source 列：web, book, paper, ...</span></span></code></pre></div><p>这对训练数据很有用。比如训练时只需要读取 <code>text</code> 这一列，就可以尽量避免把 <code>id</code>、<code>source</code> 或其他元信息全部读出来。</p><p>常见读取方式类似这样：</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> pyarrow.parquet </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">as</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> pq</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">pf </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> pq.ParquetFile(filepath)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">row_group </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> pf.read_row_group(row_group_idx)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">texts </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> row_group.column(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;text&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">).to_pylist()</span></span></code></pre></div><p>这段代码大致意思是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>打开一个 parquet 文件</span></span>
<span class="line"><span>↓</span></span>
<span class="line"><span>读取其中一个 row group</span></span>
<span class="line"><span>↓</span></span>
<span class="line"><span>取出 text 这一列</span></span>
<span class="line"><span>↓</span></span>
<span class="line"><span>转成 Python list</span></span></code></pre></div><h2 id="row-group-按块读取" tabindex="-1">Row group：按块读取 <a class="header-anchor" href="#row-group-按块读取" aria-label="Permalink to &quot;Row group：按块读取&quot;">​</a></h2><p>Parquet 文件内部还会分成一块一块的数据，叫 <strong>row group</strong>。</p><p>可以理解成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>一个 parquet 文件</span></span>
<span class="line"><span>├── row group 0</span></span>
<span class="line"><span>├── row group 1</span></span>
<span class="line"><span>├── row group 2</span></span>
<span class="line"><span>└── ...</span></span></code></pre></div><p>每个 row group 里面有一批行。读取时不需要一次把整个大文件读进内存，而是可以一次读一个 row group。</p><p>这对大模型训练很重要，因为训练数据太大，不可能一次性全部加载到内存里。</p><h2 id="我的理解" tabindex="-1">我的理解 <a class="header-anchor" href="#我的理解" aria-label="Permalink to &quot;我的理解&quot;">​</a></h2><p>如果从大模型训练数据的角度看，可以粗略这样分：</p><ul><li>JSONL 更适合中小规模数据、人工检查、指令微调数据。</li><li>Parquet 更适合大规模预训练数据，因为它压缩好、读取快，支持按列和按块读取。</li><li>CSV 简单但表达能力弱，更适合作为小表格或临时数据。</li><li>JSON 结构灵活，但大规模逐条读取时不如 JSONL 顺手。</li></ul><p>一句话总结：</p><blockquote><p>Parquet 是一种适合存储和读取大规模表格数据的高效文件格式。大模型预训练数据常用它来保存海量文本，因为它压缩好、读取快，支持按列读取和分块读取。</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("topics/llm/pretraining/预训练数据格式.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _______ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _______ as default
};
