import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"","description":"","frontmatter":{},"headers":[],"relativePath":"topics/algorithms/clustering/聚类算法工程实现.md","filePath":"topics/algorithms/clustering/聚类算法工程实现.md"}');
const _sfc_main = { name: "topics/algorithms/clustering/聚类算法工程实现.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p>这篇是经典的 <strong>CluStream</strong> 论文，和刚才 EverMemBench 不一样：<strong>这篇是真正提出算法框架的论文</strong>。</p><p>论文题目是 <strong>A Framework for Clustering Evolving Data Streams</strong>，核心问题是： 数据流不断到来、不能反复扫描，而且数据分布会随时间变化。传统一次性聚类或者 one-pass k-means 会被“过时历史”支配，无法回答“最近一个月的簇是什么”“去年和现在的簇怎么变了”这类问题。</p><h2 id="一句话概括" tabindex="-1">一句话概括 <a class="header-anchor" href="#一句话概括" aria-label="Permalink to &quot;一句话概括&quot;">​</a></h2><p>这篇论文提出 <strong>CluStream</strong>：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>在线阶段：维护很多细粒度 micro-cluster</span></span>
<span class="line"><span>离线阶段：按用户指定时间窗口，把 micro-cluster 聚成 macro-cluster</span></span>
<span class="line"><span>时间存储：用 pyramidal time frame 保存历史快照</span></span></code></pre></div><p>它本质上是一个<strong>流式数据的时间感知聚类框架</strong>。</p><h2 id="为什么不能直接用普通-k-means" tabindex="-1">为什么不能直接用普通 k-means？ <a class="header-anchor" href="#为什么不能直接用普通-k-means" aria-label="Permalink to &quot;为什么不能直接用普通 k-means？&quot;">​</a></h2><p>因为普通 k-means 或简单 one-pass clustering 有几个问题：</p><p>第一，数据流不能回头扫描。 第二，数据一直演化，早期数据可能已经不代表当前状态。 第三，如果两个簇早期被合并了，后面想再拆开就很难。 第四，用户可能想查不同时间窗口，比如最近 1 小时、最近 1 天、最近 1 年。普通算法无法高效支持。</p><p>所以论文把问题拆成两层：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>online micro-clustering：快速吸收数据，保存统计摘要</span></span>
<span class="line"><span>offline macro-clustering：用户查询时，再基于摘要做聚类</span></span></code></pre></div><h2 id="核心算法-1-micro-cluster" tabindex="-1">核心算法 1：Micro-cluster <a class="header-anchor" href="#核心算法-1-micro-cluster" aria-label="Permalink to &quot;核心算法 1：Micro-cluster&quot;">​</a></h2><p>Micro-cluster 是这篇论文最核心的表示。</p><p>它不是保存原始点，而是保存一个簇的统计量：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>CF2x：每个维度的平方和</span></span>
<span class="line"><span>CF1x：每个维度的和</span></span>
<span class="line"><span>CF2t：时间戳平方和</span></span>
<span class="line"><span>CF1t：时间戳和</span></span>
<span class="line"><span>n：点的数量</span></span></code></pre></div><p>所以一个 d 维 micro-cluster 是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>( CF2x, CF1x, CF2t, CF1t, n )</span></span></code></pre></div><p>这个设计的关键是：它有<strong>可加性</strong>和<strong>可减性</strong>。 两个 micro-cluster 可以相加，表示合并；两个时间快照之间可以相减，得到某个时间窗口内的统计摘要。</p><p>这点非常重要。因为它让系统不需要保存所有原始数据，也能回答：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>最近 h 时间窗口内的数据形成了什么簇？</span></span></code></pre></div><h2 id="核心算法-2-pyramidal-time-frame" tabindex="-1">核心算法 2：Pyramidal Time Frame <a class="header-anchor" href="#核心算法-2-pyramidal-time-frame" aria-label="Permalink to &quot;核心算法 2：Pyramidal Time Frame&quot;">​</a></h2><p>如果每个时刻都保存一次 micro-cluster 快照，存储会爆炸。</p><p>所以论文提出 <strong>pyramidal time frame</strong>： 越近的历史保存得越密，越远的历史保存得越稀。</p><p>类似这样：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>最近几秒：高频快照</span></span>
<span class="line"><span>最近几分钟：稍稀疏</span></span>
<span class="line"><span>最近几小时：更稀疏</span></span>
<span class="line"><span>很久以前：只保留少量关键快照</span></span></code></pre></div><p>论文证明，用这种方式可以用较少快照近似任意用户指定的时间窗口。例如它给了一个极端例子：如果数据流跑 100 年，按秒级粒度，在某些参数下也只需要很有限的快照数量；提高参数后可以把任意时间窗口近似到很高精度。</p><p>这个思想和长期记忆很像：<strong>近事保细，远事保粗</strong>。</p><h2 id="核心算法-3-在线维护-micro-cluster" tabindex="-1">核心算法 3：在线维护 micro-cluster <a class="header-anchor" href="#核心算法-3-在线维护-micro-cluster" aria-label="Permalink to &quot;核心算法 3：在线维护 micro-cluster&quot;">​</a></h2><p>新数据点来了以后，算法大概这样处理：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 找到离新点最近的 micro-cluster</span></span>
<span class="line"><span>2. 判断这个点是否落在该 micro-cluster 的边界内</span></span>
<span class="line"><span>3. 如果在边界内：吸收到这个 micro-cluster</span></span>
<span class="line"><span>4. 如果不在边界内：新建一个 micro-cluster</span></span>
<span class="line"><span>5. 如果 micro-cluster 数量超限：</span></span>
<span class="line"><span>   - 优先删除不活跃 / 过时的 micro-cluster</span></span>
<span class="line"><span>   - 如果不能删，就合并最近的两个 micro-cluster</span></span>
<span class="line"><span>6. 按 pyramidal time frame 定期保存快照</span></span></code></pre></div><p>这里有个细节： 它不是简单删除“点数最少”的 micro-cluster，而是计算 <strong>relevance stamp</strong>，也就是这个 micro-cluster 最近是否还活跃。因为一个簇过去可能很大，但现在已经不活跃了，对当前聚类意义就不大。</p><p>这点对记忆系统也很有启发： 不是“用得少就删”，而是看它在当前时间窗口里是否还相关。</p><h2 id="核心算法-4-离线-macro-cluster" tabindex="-1">核心算法 4：离线 macro-cluster <a class="header-anchor" href="#核心算法-4-离线-macro-cluster" aria-label="Permalink to &quot;核心算法 4：离线 macro-cluster&quot;">​</a></h2><p>用户查询时会给两个参数：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>h：时间窗口，例如最近 7 天</span></span>
<span class="line"><span>k：想要几个大簇</span></span></code></pre></div><p>系统会找当前快照和过去某个快照，然后利用 micro-cluster 的<strong>可减性</strong>，得到这个时间窗口内的 micro-cluster 集合。</p><p>然后把这些 micro-cluster 当成 pseudo-points，再用修改版 k-means 聚成 k 个 macro-cluster。修改点包括：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. 初始化种子不是随机点，而是按 micro-cluster 的点数加权采样</span></span>
<span class="line"><span>2. 距离计算使用 micro-cluster 的中心</span></span>
<span class="line"><span>3. 更新中心时使用 weighted centroid</span></span></code></pre></div><p>也就是说：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>原始数据点太多，不直接聚类；</span></span>
<span class="line"><span>先压缩成 micro-cluster；</span></span>
<span class="line"><span>查询时再把 micro-cluster 聚成 macro-cluster。</span></span></code></pre></div><h2 id="核心算法-5-演化分析" tabindex="-1">核心算法 5：演化分析 <a class="header-anchor" href="#核心算法-5-演化分析" aria-label="Permalink to &quot;核心算法 5：演化分析&quot;">​</a></h2><p>这篇论文还有一个重要功能：比较两个时间点的簇变化。</p><p>用户输入：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>t1：过去时间点</span></span>
<span class="line"><span>t2：当前或另一个时间点</span></span>
<span class="line"><span>h：比较窗口</span></span></code></pre></div><p>系统比较：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>(t1 - h, t1) 的簇</span></span>
<span class="line"><span>和</span></span>
<span class="line"><span>(t2 - h, t2) 的簇</span></span></code></pre></div><p>然后把变化分成三类：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>M_added：新增的 micro-cluster</span></span>
<span class="line"><span>M_deleted：消失的 micro-cluster</span></span>
<span class="line"><span>M_retained：保留但可能变化的 micro-cluster</span></span></code></pre></div><p>这就能回答：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>有没有新簇出现？</span></span>
<span class="line"><span>有没有旧簇消失？</span></span>
<span class="line"><span>有没有簇的位置或性质发生变化？</span></span></code></pre></div><p>论文专门说，micro-cluster 的 idlist 可以用来追踪这些变化。</p><h2 id="实验结论" tabindex="-1">实验结论 <a class="header-anchor" href="#实验结论" aria-label="Permalink to &quot;实验结论&quot;">​</a></h2><p>实验对比的是 CluStream 和 STREAM。论文使用了 KDD-CUP&#39;99 网络入侵数据集、KDD-CUP&#39;98 捐赠数据集，以及合成数据。结果显示，CluStream 在快速演化的数据流上明显优于 STREAM，尤其在网络入侵数据上，SSQ 指标可以低几个数量级。论文认为优势来自两个设计：pyramidal time frame 能近似任意时间窗口，micro-cluster 保存了足够细粒度的统计信息。</p><h2 id="和你做长期记忆有什么关系" tabindex="-1">和你做长期记忆有什么关系？ <a class="header-anchor" href="#和你做长期记忆有什么关系" aria-label="Permalink to &quot;和你做长期记忆有什么关系？&quot;">​</a></h2><p>这篇虽然是数据流聚类，不是 LLM memory，但它对你很有启发。</p><p>你现在关心的是长期记忆、主动关心、用户创意助手。CluStream 给了一个非常清晰的工程范式：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>不要把所有历史都平铺保存；</span></span>
<span class="line"><span>而是在线维护细粒度摘要；</span></span>
<span class="line"><span>按时间快照保存；</span></span>
<span class="line"><span>查询时按时间窗口重构；</span></span>
<span class="line"><span>再做高层聚合。</span></span></code></pre></div><p>映射到记忆系统可以是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>原始对话 / 浏览行为 = data stream</span></span>
<span class="line"><span>micro-cluster = 小型记忆单元 / 事件簇</span></span>
<span class="line"><span>pyramidal snapshots = 近细远粗的记忆快照</span></span>
<span class="line"><span>macro-cluster = 当前主题 / 用户阶段 / 创意方向</span></span>
<span class="line"><span>evolution analysis = 用户兴趣、项目方向、偏好变化</span></span></code></pre></div><p>比如用户早期一直在聊“记忆系统”，后来转向“创意助手”，再后来收敛到“真实痛点、流程、竞品分析”。 如果用 CluStream 思路，你不是简单存一堆聊天记录，而是维护“主题簇随时间的演化”。</p><h2 id="最值得借鉴的一句话" tabindex="-1">最值得借鉴的一句话 <a class="header-anchor" href="#最值得借鉴的一句话" aria-label="Permalink to &quot;最值得借鉴的一句话&quot;">​</a></h2><p>我觉得这篇论文对你最有价值的点是：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>长期系统不能只保存最终聚类结果，</span></span>
<span class="line"><span>而应该保存足够细粒度、可加可减、可按时间窗口重构的中间摘要。</span></span></code></pre></div><p>这比单纯 embedding memory 更工程化。 如果你要设计 Mnemo 的记忆层，CluStream 的思想可以转成：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>MemoryStream：</span></span>
<span class="line"><span>在线阶段维护事件级 memory micro-clusters；</span></span>
<span class="line"><span>定期保存时间快照；</span></span>
<span class="line"><span>查询时按时间窗口重建相关记忆；</span></span>
<span class="line"><span>再聚合成当前用户状态、兴趣状态、项目状态。</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("topics/algorithms/clustering/聚类算法工程实现.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const ________ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  ________ as default
};
